// SmartSend AUREV OS - Notion Campaign Reports Integration
// Auto-generates campaign documentation and reports in Notion

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const supabase = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
);

const NOTION_KEY = Deno.env.get("NOTION_API_KEY")!;
const NOTION_DB_ID = Deno.env.get("NOTION_DATABASE_ID")!;

interface CampaignSummary {
  campaign_id: string;
  name: string;
  total_leads: number;
  sent: number;
  opened: number;
  clicked: number;
  replied: number;
  conversion_rate: number;
  start_date: string;
  end_date?: string;
}

async function createNotionPage(summary: CampaignSummary): Promise<string | null> {
  try {
    const response = await fetch("https://api.notion.com/v1/pages", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${NOTION_KEY}`,
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28",
      },
      body: JSON.stringify({
        parent: { database_id: NOTION_DB_ID },
        properties: {
          Name: {
            title: [{ text: { content: summary.name || `Campaign ${summary.campaign_id}` } }],
          },
          Date: {
            date: { start: summary.start_date },
          },
          Status: {
            select: { name: summary.end_date ? "Complete" : "Active" },
          },
          "Total Leads": {
            number: summary.total_leads,
          },
          Sent: {
            number: summary.sent,
          },
          Opens: {
            number: summary.opened,
          },
          Clicks: {
            number: summary.clicked,
          },
          Replies: {
            number: summary.replied,
          },
          "Conversion Rate": {
            number: Math.round(summary.conversion_rate * 100) / 100,
          },
        },
        children: [
          {
            object: "block",
            type: "paragraph",
            paragraph: {
              rich_text: [
                {
                  type: "text",
                  text: {
                    content: `Auto-generated by AUREV OS ⚡\n\n` +
                      `Campaign ID: ${summary.campaign_id}\n` +
                      `Total Leads: ${summary.total_leads}\n` +
                      `Emails Sent: ${summary.sent}\n` +
                      `Opens: ${summary.opened}\n` +
                      `Clicks: ${summary.clicked}\n` +
                      `Replies: ${summary.replied}\n` +
                      `Conversion Rate: ${(summary.conversion_rate * 100).toFixed(2)}%`,
                  },
                },
              ],
            },
          },
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Notion API error:", errorText);
      return null;
    }

    const data = await response.json();
    return data.id || null;
  } catch (error) {
    console.error("Error creating Notion page:", error);
    return null;
  }
}

async function getCampaignSummary(campaignId: string): Promise<CampaignSummary | null> {
  try {
    // Fetch campaign details
    const { data: campaign, error: campaignError } = await supabase
      .from("campaigns")
      .select("id, name, created_at, status")
      .eq("id", campaignId)
      .single();

    if (campaignError || !campaign) {
      console.error("Error fetching campaign:", campaignError);
      return null;
    }

    // Fetch campaign stats
    const { data: stats, error: statsError } = await supabase
      .from("campaign_analytics")
      .select("total_leads, sent, opened, clicked, replied")
      .eq("campaign_id", campaignId)
      .single();

    const summary: CampaignSummary = {
      campaign_id: campaignId,
      name: campaign.name || `Campaign ${campaignId}`,
      total_leads: stats?.total_leads || 0,
      sent: stats?.sent || 0,
      opened: stats?.opened || 0,
      clicked: stats?.clicked || 0,
      replied: stats?.replied || 0,
      conversion_rate: stats?.total_leads ? (stats.replied || 0) / stats.total_leads : 0,
      start_date: campaign.created_at,
      end_date: campaign.status === "completed" ? new Date().toISOString() : undefined,
    };

    return summary;
  } catch (error) {
    console.error("Error building campaign summary:", error);
    return null;
  }
}

Deno.serve(async (req) => {
  try {
    const body = await req.json();
    const { campaign_id } = body;

    if (!campaign_id) {
      return new Response(
        JSON.stringify({ error: "campaign_id is required" }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    // Get campaign summary
    const summary = await getCampaignSummary(campaign_id);

    if (!summary) {
      return new Response(
        JSON.stringify({ error: "Failed to get campaign summary" }),
        { status: 500, headers: { "Content-Type": "application/json" } }
      );
    }

    // Create Notion page
    const pageId = await createNotionPage(summary);

    if (!pageId) {
      return new Response(
        JSON.stringify({ error: "Failed to create Notion page" }),
        { status: 500, headers: { "Content-Type": "application/json" } }
      );
    }

    return new Response(
      JSON.stringify({
        success: true,
        notion_page_id: pageId,
        campaign_id,
        timestamp: new Date().toISOString(),
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Unexpected error:", error);
    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : "Unknown error",
      }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
});
