import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServer } from "@/lib/supabaseServer";
import { getCurrentOrgId } from "@/lib/org-helpers";
import { Task } from "../../route";
import { logTaskCompleted } from "@/lib/contactActivity";
import { logTaskCompletedV3 } from "@/lib/contactActivityV3";

/**
 * POST /api/tasks/[id]/complete
 * Mark a task as completed
 */
export async function POST(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = createSupabaseServer();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const taskId = params.id;

    // Get current org_id
    const orgId = await getCurrentOrgId();
    if (!orgId) {
      return NextResponse.json({ error: "No organization found" }, { status: 400 });
    }

    // Update task to completed
    const { data: task, error } = await supabase
      .from("tasks")
      .update({
        completed: true,
        status: 'completed',
        completed_at: new Date().toISOString(),
      })
      .eq("id", taskId)
      .eq("org_id", orgId)
      .select("*")
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    if (!task) {
      return NextResponse.json({ error: "Task not found" }, { status: 404 });
    }

    // Log activity timeline event
    if (task.contact_id) {
      try {
        // Log to v2 activity_events table (existing)
        await logTaskCompleted(orgId, task.contact_id, {
          taskId: task.id,
          title: task.title,
          userId: user.id,
        });

        // Log to v3 contact_activity table (Block 13500)
        await logTaskCompletedV3(task.contact_id, {
          taskTitle: task.title,
          createdBy: user.id,
        });

        // Notify original assigner if different from completer
        if (task.created_by && task.created_by !== user.id) {
          await supabase.rpc("create_task_completed_notification", {
            p_org_id: orgId,
            p_user_id: task.created_by,
            p_task_id: task.id,
            p_contact_id: task.contact_id,
          });
        }
      } catch (err) {
        console.error("Error logging task activity:", err);
        // Don't fail the request if logging fails
      }
    }

    // Transform to API format
    const transformed: Task = {
      id: task.id,
      orgId: task.org_id,
      contactId: task.contact_id || undefined,
      replyThreadId: task.reply_thread_id || undefined,
      campaignId: task.campaign_id || undefined,
      assignedTo: task.assigned_to || undefined,
      title: task.title,
      notes: task.notes || undefined,
      dueAt: task.due_at,
      dueDate: task.due_date || undefined,
      priority: task.priority || 'normal',
      status: task.status || 'completed',
      completed: task.completed,
      completedAt: task.completed_at || undefined,
      createdAt: task.created_at,
      updatedAt: task.updated_at,
      autoGenerated: task.auto_generated,
      autoType: task.auto_type || undefined,
      createdBy: task.created_by || undefined,
    };

    return NextResponse.json({ data: transformed });
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}

