// Block 13900 — Smart Tasks v2 Global Task Board
// Drag & drop task board with columns: Today, Tomorrow, This Week, Later

"use client";

import { useEffect, useState } from "react";
import { Task } from "@/src/app/api/tasks/route";
import { CheckCircle2, Circle, AlertCircle, Clock, Phone, Mail, Calendar, TrendingUp } from "lucide-react";

type TaskGroup = {
  overdue: Task[];
  today: Task[];
  tomorrow: Task[];
  thisWeek: Task[];
  later: Task[];
};

const PRIORITY_COLORS = {
  high: "text-red-600 bg-red-50 border-red-200",
  medium: "text-yellow-600 bg-yellow-50 border-yellow-200",
  low: "text-blue-600 bg-blue-50 border-blue-200",
};

const TYPE_ICONS = {
  call: Phone,
  text: Phone,
  email: Mail,
  inspection: Calendar,
  follow_up: Clock,
  send_estimate: Calendar,
  re_engage: Clock,
  answer_question: AlertCircle,
  review_damage: AlertCircle,
  insurance_support: AlertCircle,
};

export default function TasksPage() {
  const [tasks, setTasks] = useState<TaskGroup>({
    overdue: [],
    today: [],
    tomorrow: [],
    thisWeek: [],
    later: [],
  });
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<"all" | "high" | "medium" | "low">("all");

  useEffect(() => {
    loadTasks();
  }, [filter]);

  async function loadTasks() {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      params.set("status", "open");
      if (filter !== "all") {
        params.set("priority", filter);
      }

      const res = await fetch(`/api/tasks?${params.toString()}`);
      const json = await res.json();
      
      if (json.grouped) {
        setTasks(json.grouped);
      } else {
        // Fallback grouping
        const grouped: TaskGroup = {
          overdue: [],
          today: [],
          tomorrow: [],
          thisWeek: [],
          later: [],
        };
        (json.data || []).forEach((task: Task) => {
          const dueDate = new Date(task.dueAt);
          const now = new Date();
          const today = new Date(now.setHours(0, 0, 0, 0));
          const tomorrow = new Date(today);
          tomorrow.setDate(tomorrow.getDate() + 1);
          const endOfWeek = new Date(today);
          endOfWeek.setDate(today.getDate() + (7 - today.getDay()));

          if (dueDate < today) {
            grouped.overdue.push(task);
          } else if (dueDate.toDateString() === today.toDateString()) {
            grouped.today.push(task);
          } else if (dueDate.toDateString() === tomorrow.toDateString()) {
            grouped.tomorrow.push(task);
          } else if (dueDate <= endOfWeek) {
            grouped.thisWeek.push(task);
          } else {
            grouped.later.push(task);
          }
        });
        setTasks(grouped);
      }
    } catch (error) {
      console.error("Error loading tasks:", error);
    } finally {
      setLoading(false);
    }
  }

  const handleCompleteTask = async (taskId: string) => {
    try {
      const res = await fetch(`/api/tasks/${taskId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: "completed", completed: true }),
      });

      if (res.ok) {
        loadTasks(); // Reload tasks
      }
    } catch (error) {
      console.error("Error completing task:", error);
    }
  };

  const TaskCard = ({ task }: { task: Task }) => {
    const Icon = TYPE_ICONS[task.type as keyof typeof TYPE_ICONS] || Clock;
    const priorityColor = PRIORITY_COLORS[task.priority as keyof typeof PRIORITY_COLORS] || PRIORITY_COLORS.medium;
    const isOverdue = new Date(task.dueAt) < new Date();

    return (
      <div
        className={`border rounded-lg p-3 bg-white hover:shadow-md transition-shadow ${
          isOverdue ? "border-red-300 bg-red-50" : ""
        }`}
      >
        <div className="flex items-start justify-between gap-2">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <Icon className="h-3.5 w-3.5 text-gray-400 flex-shrink-0" />
              <span className={`text-xs font-medium px-1.5 py-0.5 rounded border ${priorityColor}`}>
                {task.priority === "high" ? "🔥" : task.priority === "medium" ? "⚠️" : "🟦"}
              </span>
              {task.autoGenerated && (
                <span className="text-xs text-gray-400">Auto</span>
              )}
            </div>
            <p className="text-sm text-gray-900 font-medium mb-1 line-clamp-2">
              {task.title}
            </p>
            {task.notes && (
              <p className="text-xs text-gray-500 mb-1 line-clamp-1">{task.notes}</p>
            )}
            <div className="flex items-center gap-2 text-xs text-gray-500">
              <Clock className="h-3 w-3" />
              <span className={isOverdue ? "text-red-600 font-medium" : ""}>
                {new Date(task.dueAt).toLocaleDateString("en-US", {
                  month: "short",
                  day: "numeric",
                  hour: "numeric",
                  minute: "2-digit",
                })}
              </span>
            </div>
          </div>
          <button
            onClick={() => handleCompleteTask(task.id)}
            className="flex-shrink-0 p-1 hover:bg-gray-100 rounded"
            title="Mark as complete"
          >
            <Circle className="h-4 w-4 text-gray-400 hover:text-green-600" />
          </button>
        </div>
      </div>
    );
  };

  const TaskColumn = ({ title, tasks, color }: { title: string; tasks: Task[]; color: string }) => (
    <div className="flex-1 min-w-0 flex flex-col">
      <div className={`${color} p-3 rounded-t-lg`}>
        <h3 className="font-semibold text-sm text-gray-900">{title}</h3>
        <p className="text-xs text-gray-600 mt-0.5">{tasks.length} tasks</p>
      </div>
      <div className="flex-1 overflow-y-auto p-3 space-y-2 bg-gray-50 rounded-b-lg border border-t-0">
        {tasks.length === 0 ? (
          <div className="text-xs text-gray-400 text-center py-8">No tasks</div>
        ) : (
          tasks.map((task) => <TaskCard key={task.id} task={task} />)
        )}
      </div>
    </div>
  );

  if (loading) {
    return (
      <div className="h-[calc(100vh-64px)] flex items-center justify-center">
        <div className="text-gray-500">Loading tasks...</div>
      </div>
    );
  }

  const totalTasks = tasks.overdue.length + tasks.today.length + tasks.tomorrow.length + tasks.thisWeek.length + tasks.later.length;

  return (
    <div className="h-[calc(100vh-64px)] flex flex-col">
      {/* Header */}
      <div className="border-b bg-white p-4">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-xl font-semibold">Task Board</h1>
            <p className="text-sm text-gray-500 mt-1">
              {totalTasks} {totalTasks === 1 ? "task" : "tasks"} • {tasks.overdue.length} overdue
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => setFilter("all")}
              className={`px-3 py-1.5 text-xs rounded ${
                filter === "all" ? "bg-blue-600 text-white" : "bg-gray-100 text-gray-700"
              }`}
            >
              All
            </button>
            <button
              onClick={() => setFilter("high")}
              className={`px-3 py-1.5 text-xs rounded flex items-center gap-1 ${
                filter === "high" ? "bg-red-600 text-white" : "bg-gray-100 text-gray-700"
              }`}
            >
              🔥 High
            </button>
            <button
              onClick={() => setFilter("medium")}
              className={`px-3 py-1.5 text-xs rounded flex items-center gap-1 ${
                filter === "medium" ? "bg-yellow-600 text-white" : "bg-gray-100 text-gray-700"
              }`}
            >
              ⚠️ Medium
            </button>
            <button
              onClick={() => setFilter("low")}
              className={`px-3 py-1.5 text-xs rounded flex items-center gap-1 ${
                filter === "low" ? "bg-blue-600 text-white" : "bg-gray-100 text-gray-700"
              }`}
            >
              🟦 Low
            </button>
          </div>
        </div>
      </div>

      {/* Task Board */}
      <div className="flex-1 overflow-x-auto p-4">
        <div className="flex gap-4 h-full min-w-max">
          <TaskColumn
            title="Overdue"
            tasks={tasks.overdue}
            color="bg-red-100 border-red-200"
          />
          <TaskColumn
            title="Today"
            tasks={tasks.today}
            color="bg-orange-100 border-orange-200"
          />
          <TaskColumn
            title="Tomorrow"
            tasks={tasks.tomorrow}
            color="bg-yellow-100 border-yellow-200"
          />
          <TaskColumn
            title="This Week"
            tasks={tasks.thisWeek}
            color="bg-blue-100 border-blue-200"
          />
          <TaskColumn
            title="Later"
            tasks={tasks.later}
            color="bg-gray-100 border-gray-200"
          />
        </div>
      </div>
    </div>
  );
}





















































