// deno-lint-ignore-file no-explicit-any

/** Lightweight HTML → text (no external deps). */
export function htmlToText(html: string): string {
  if (!html) return "";

  let s = html
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<head[\s\S]*?<\/head>/gi, " ")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n")
    .replace(/<\/div>/gi, "\n")
    .replace(/<\/li>/gi, "\n• ")
    .replace(/<li>/gi, "• ")
    .replace(/<\/h\d>/gi, "\n")
    .replace(/<[^>]+>/g, " "); // strip remaining tags

  // decode a few common entities
  s = s
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"');

  return s;
}

/** Remove forwarded/quoted history and “On … wrote:” blocks. */
export function stripQuoted(text: string): string {
  if (!text) return "";
  const lines = text.split(/\r?\n/);

  const cutPatterns = [
    /^\s*>/, // traditional quotes
    /^\s*on .*wrote:$/i,
    /^\s*de: .*$/i, // ES/FR/DE "De:", "Von:" etc.
    /^\s*von: .*$/i,
    /^\s*am .* schrieb .*:$/i,
    /^\s*-----\s*Original\s*Message\s*-----/i,
    /^\s*from:\s.*$/i,
    /^\s*sent:\s.*$/i,
  ];

  const kept: string[] = [];
  for (const ln of lines) {
    if (cutPatterns.some((re) => re.test(ln))) break;
    kept.push(ln);
  }
  return kept.join("\n");
}

/** Remove long legal footers / confidentiality notices / logos alt text. */
export function stripFooters(text: string): string {
  const MAX_LEN = 4000; // hard cap after cleaning
  let s = text;

  // common legal blocks start markers
  const footerMarkers = [
    /this message (and any attachments) (is|are) intended/i,
    /confidentiality notice/i,
    /please consider the environment/i,
    /este mensaje.*confidencial/i,
    /ce message.*confidentiel/i,
    /avis?: de confidentialité/i,
    /DISCLAIMER:/i,
    /AUTOGENERATED/i,
  ];
  for (const re of footerMarkers) {
    const m = s.search(re);
    if (m > -1) s = s.slice(0, m);
  }

  // truncate repeated whitespace & links dumps
  s = s.replace(/\s{3,}/g, " ").replace(/https?:\/\/\S+/gi, "").trim();

  // hard cap (avoid 10k-char signatures)
  if (s.length > MAX_LEN) s = s.slice(0, MAX_LEN);
  return s;
}

/** Strip common signature delimiters and lines after that. */
export function stripSignature(text: string): string {
  const sigMarkers = [
    /^--\s*$/, // classic sig delimiter
    /^sent from my (iphone|ipad|android|mobile)/i,
    /^best regards[,]?$/i,
    /^regards[,]?$/i,
    /^cheers[,]?$/i,
    /^sincerely[,]?$/i,
    /^thanks[,]?$/i,
    /^thank you[,]?$/i,
  ];
  const out: string[] = [];
  for (const ln of text.split(/\r?\n/)) {
    if (sigMarkers.some((re) => re.test(ln.trim()))) break;
    out.push(ln);
  }
  return out.join("\n");
}

/** Collapse to tidy snippet for NLP. */
export function normalizeWhitespace(text: string): string {
  return text
    .replace(/\r/g, "")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

/** Master sanitize pipeline. Prefer plaintext, but accept HTML fallback. */
export function sanitizeEmailBody(input: {
  plaintext?: string;
  html?: string;
}): string {
  const base = input.plaintext?.trim()?.length
    ? input.plaintext!
    : htmlToText(input.html || "");
  const s1 = stripQuoted(base);
  const s2 = stripSignature(s1);
  const s3 = stripFooters(s2);
  const s4 = normalizeWhitespace(s3);
  // keep first ~1,200 chars to focus on core semantics
  return s4.length > 1200 ? s4.slice(0, 1200) : s4;
}

// deno-lint-ignore-file no-explicit-any

/** Lightweight HTML → text (no external deps). */
export function htmlToText(html: string): string {
  if (!html) return "";

  let s = html
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<head[\s\S]*?<\/head>/gi, " ")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n")
    .replace(/<\/div>/gi, "\n")
    .replace(/<\/li>/gi, "\n• ")
    .replace(/<li>/gi, "• ")
    .replace(/<\/h\d>/gi, "\n")
    .replace(/<[^>]+>/g, " "); // strip remaining tags

  // decode a few common entities
  s = s
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"');

  return s;
}

/** Remove forwarded/quoted history and “On … wrote:” blocks. */
export function stripQuoted(text: string): string {
  if (!text) return "";

  const lines = text.split(/\r?\n/);

  const cutPatterns = [
    /^\s*>/, // traditional quotes
    /^\s*on .*wrote:$/i,
    /^\s*de: .*$/i, // ES/FR/DE "De:", "Von:" etc.
    /^\s*von: .*$/i,
    /^\s*am .* schrieb .*:$/i,
    /^\s*-----\s*Original\s*Message\s*-----/i,
    /^\s*from:\s.*$/i,
    /^\s*sent:\s.*$/i,
  ];

  const kept: string[] = [];
  for (const ln of lines) {
    if (cutPatterns.some((re) => re.test(ln))) break;
    kept.push(ln);
  }

  return kept.join("\n");
}

/** Remove long legal footers / confidentiality notices / logos alt text. */
export function stripFooters(text: string): string {
  const MAX_LEN = 4000; // hard cap after cleaning
  let s = text;

  // common legal blocks start markers
  const footerMarkers = [
    /this message (and any attachments) (is|are) intended/i,
    /confidentiality notice/i,
    /please consider the environment/i,
    /este mensaje.*confidencial/i,
    /ce message.*confidentiel/i,
    /avis?: de confidentialité/i,
    /DISCLAIMER:/i,
    /AUTOGENERATED/i,
  ];

  for (const re of footerMarkers) {
    const m = s.search(re);
    if (m > -1) s = s.slice(0, m);
  }

  // truncate repeated whitespace & links dumps
  s = s.replace(/\s{3,}/g, " ").replace(/https?:\/\/\S+/gi, "").trim();

  // hard cap (avoid 10k-char signatures)
  if (s.length > MAX_LEN) s = s.slice(0, MAX_LEN);

  return s;
}

/** Strip common signature delimiters and lines after that. */
export function stripSignature(text: string): string {
  const sigMarkers = [
    /^--\s*$/, // classic sig delimiter
    /^sent from my (iphone|ipad|android|mobile)/i,
    /^best regards[,]?$/i,
    /^regards[,]?$/i,
    /^cheers[,]?$/i,
    /^sincerely[,]?$/i,
    /^thanks[,]?$/i,
    /^thank you[,]?$/i,
  ];

  const out: string[] = [];
  for (const ln of text.split(/\r?\n/)) {
    if (sigMarkers.some((re) => re.test(ln.trim()))) break;
    out.push(ln);
  }

  return out.join("\n");
}

/** Collapse to tidy snippet for NLP. */
export function normalizeWhitespace(text: string): string {
  return text
    .replace(/\r/g, "")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

/** Master sanitize pipeline. Prefer plaintext, but accept HTML fallback. */
export function sanitizeEmailBody(input: {
  plaintext?: string;
  html?: string;
}): string {
  const base = input.plaintext?.trim()?.length
    ? input.plaintext!
    : htmlToText(input.html || "");

  const s1 = stripQuoted(base);
  const s2 = stripSignature(s1);
  const s3 = stripFooters(s2);
  const s4 = normalizeWhitespace(s3);

  // keep first ~1,200 chars to focus on core semantics
  return s4.length > 1200 ? s4.slice(0, 1200) : s4;
}


