// Block 255900 — SmartSend AI Estimating Engine v2
// Instant Proposal Creator (Multi-Option: Good/Better/Best)
// POST /api/estimates/v2/proposals/create

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createServiceClient } from "@/lib/supabase/server";

export async function POST(req: NextRequest) {
  try {
    const supabase = createClient();
    const serviceSupabase = createServiceClient();

    // Authenticate
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const {
      estimate_id,
      lead_id,
      options = "single", // 'single' or 'multi'
      good_option = null,
      better_option = null,
      best_option = null,
      include_photos = true,
      include_measurement_report = true,
      include_warranty = true,
    } = body;

    if (!estimate_id) {
      return NextResponse.json(
        { error: "estimate_id is required" },
        { status: 400 }
      );
    }

    // Get estimate with full details
    const { data: estimate, error: estimateError } = await serviceSupabase
      .from("estimates")
      .select(`
        *,
        lead:leads(*),
        job:jobs(*)
      `)
      .eq("id", estimate_id)
      .single();

    if (estimateError || !estimate) {
      return NextResponse.json(
        { error: "Estimate not found" },
        { status: 404 }
      );
    }

    // Get measurement and materials
    const measurement = estimate.measurement || {};
    const materials = estimate.materials || [];
    const breakdown = estimate.breakdown || {};

    // Build proposal data
    let proposalData: any = {
      estimate_id,
      lead_id: lead_id || estimate.lead_id,
      org_id: estimate.org_id,
      metadata: {
        options,
        generated_at: new Date().toISOString(),
        generated_by: user.id,
      },
    };

    // Single option proposal
    if (options === "single") {
      proposalData.metadata.proposal_type = "single";
      proposalData.metadata.price = estimate.total_price;
      proposalData.metadata.materials = materials;
      proposalData.metadata.measurement = measurement;
      proposalData.metadata.breakdown = breakdown;
    } else {
      // Multi-option proposal (Good/Better/Best)
      const basePrice = estimate.total_price || 0;
      const baseMaterials = materials;

      proposalData.metadata.proposal_type = "multi";
      proposalData.metadata.options = {
        good: good_option || {
          name: "GOOD (Basic)",
          price: Math.round(basePrice * 0.9), // 10% discount
          description: "Traditional ridge, basic underlayment",
          materials: baseMaterials,
        },
        better: better_option || {
          name: "BETTER (Standard Recommended)",
          price: Math.round(basePrice),
          description: "High-performance underlayment + timberline shingles",
          materials: baseMaterials,
          recommended: true,
        },
        best: best_option || {
          name: "BEST (Premium)",
          price: Math.round(basePrice * 1.2), // 20% premium
          description: "Upgraded ridge, ventilation package, extended warranty",
          materials: baseMaterials,
          upgrades: [
            "Premium ridge vent system",
            "Extended warranty (25 years)",
            "Enhanced ventilation package",
          ],
        },
      };
    }

    // Include additional sections
    if (include_measurement_report) {
      proposalData.metadata.measurement_report = {
        squares: measurement.squares,
        pitch: measurement.pitch,
        facets: measurement.facets,
        ridge_length_ft: measurement.ridge_length_ft,
        hip_length_ft: measurement.hip_length_ft,
        valley_length_ft: measurement.valley_length_ft,
        eaves_length_ft: measurement.eaves_length_ft,
      };
    }

    if (include_warranty) {
      proposalData.metadata.warranty = {
        material_warranty: "30 years",
        workmanship_warranty: "5 years",
        transferable: true,
      };
    }

    // Create proposal record
    const { data: proposal, error: proposalError } = await serviceSupabase
      .from("proposals")
      .insert({
        org_id: estimate.org_id,
        estimate_id,
        lead_id: lead_id || estimate.lead_id,
        metadata: proposalData.metadata,
        pdf_url: null, // Will be generated by PDF service
        sent: false,
      })
      .select()
      .single();

    if (proposalError) {
      console.error("Error creating proposal:", proposalError);
      return NextResponse.json(
        { error: "Failed to create proposal", details: proposalError.message },
        { status: 500 }
      );
    }

    // Update estimate with proposal URL
    const proposalUrl = `/proposals/${proposal.id}`;
    await serviceSupabase
      .from("estimates")
      .update({ proposal_url: proposalUrl })
      .eq("id", estimate_id);

    return NextResponse.json({
      success: true,
      proposal: {
        ...proposal,
        proposal_url: proposalUrl,
      },
      proposal_data: proposalData.metadata,
    });
  } catch (error: any) {
    console.error("Error creating proposal:", error);
    return NextResponse.json(
      { error: error.message || "Failed to create proposal" },
      { status: 500 }
    );
  }
}





















