// Block 18100 — SmartSend Task System v3
// Full Roofing Task Engine API

import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServer } from "@/lib/supabaseServer";
import { getCurrentWorkspaceId } from "@/lib/workspace";

export type TaskTypeV3 =
  // Lead Follow-Up Tasks
  | 'lead_follow_up'
  | 'lead_reply_needed'
  | 'lead_question_asked'
  | 'lead_clarification_needed'
  | 'lead_no_reply'
  | 'lead_unread_messages'
  | 'lead_booking_intent'
  // Appointment Tasks
  | 'appointment_booked'
  | 'appointment_reminder'
  | 'appointment_missed'
  | 'appointment_reschedule'
  | 'appointment_confirmation'
  // Insurance Tasks
  | 'insurance_claim_filed'
  | 'insurance_adjuster_scheduled'
  | 'insurance_scope_received'
  | 'insurance_deductible_mentioned'
  | 'insurance_documents_uploaded'
  | 'insurance_supplement_needed'
  // Storm Tasks
  | 'storm_hail_event'
  | 'storm_wind_event'
  | 'storm_leak_detected'
  | 'storm_zone_activated'
  | 'storm_zip_affected'
  // Pipeline Tasks
  | 'pipeline_warm_followup'
  | 'pipeline_hot_booking'
  | 'pipeline_quote_checkin'
  | 'pipeline_insurance_timeline'
  // Quote Tasks
  | 'quote_sent'
  | 'quote_stale'
  | 'quote_updated'
  | 'quote_viewed'
  // Task Chaining Tasks
  | 'task_chain_next'
  // Office/Admin Tasks
  | 'admin_domain_issue'
  | 'admin_billing_issue'
  | 'admin_upload_missing_info'
  | 'admin_cleanup_duplicates'
  | 'admin_add_missing_phone'
  | 'admin_address_mismatch'
  | 'admin_bad_lead_cleanup';

export type TaskPriorityLevel = 'critical' | 'high' | 'medium' | 'low';

export type TaskStatusV3 = 'open' | 'completed' | 'overdue' | 'cancelled';

export type TaskV3 = {
  id: string;
  workspaceId: string;
  userId?: string;
  contactId?: string;
  leadId?: string;
  taskType: TaskTypeV3;
  priority: TaskPriorityLevel;
  status: TaskStatusV3;
  title: string;
  description?: string;
  notes?: string;
  dueAt: string;
  dueDate?: string;
  completedAt?: string;
  priorityScore?: number;
  metadata?: Record<string, any>;
  autoGenerated: boolean;
  autoSource?: string;
  parentTaskId?: string;
  nextTaskId?: string;
  chainPosition?: number;
  isRecurrent?: boolean;
  recurrencePattern?: string;
  recurrenceConfig?: Record<string, any>;
  nextRecurrenceAt?: string;
  pipelineStageId?: string;
  suggestedNextStage?: string;
  createdAt: string;
  updatedAt: string;
  createdBy?: string;
};

export type CreateTaskInputV3 = {
  contactId?: string;
  leadId?: string;
  taskType: TaskTypeV3;
  priority?: TaskPriorityLevel;
  title: string;
  description?: string;
  notes?: string;
  dueAt: string;
  userId?: string;
  metadata?: Record<string, any>;
  isRecurrent?: boolean;
  recurrencePattern?: string;
  recurrenceConfig?: Record<string, any>;
  pipelineStageId?: string;
  suggestedNextStage?: string;
};

/**
 * GET /api/tasks/v3
 * Get tasks with advanced filtering and daily workflow grouping
 * 
 * Query params:
 * - status: 'open' | 'completed' | 'overdue' | 'cancelled' | 'all'
 * - priority: 'critical' | 'high' | 'medium' | 'low' | 'all'
 * - taskType: TaskTypeV3
 * - assignedTo: 'me' | 'all' | userId
 * - contactId: string
 * - leadId: string
 * - overdue: boolean
 * - dailyWorkflow: boolean (returns grouped by priority)
 * - limit: number (default: 100)
 */
export async function GET(req: NextRequest) {
  try {
    const supabase = createSupabaseServer();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const searchParams = req.nextUrl.searchParams;
    const status = searchParams.get("status") || "open";
    const priority = searchParams.get("priority");
    const taskType = searchParams.get("taskType") as TaskTypeV3 | null;
    const assignedTo = searchParams.get("assignedTo") || "all";
    const contactId = searchParams.get("contactId");
    const leadId = searchParams.get("leadId");
    const overdue = searchParams.get("overdue") === "true";
    const dailyWorkflow = searchParams.get("dailyWorkflow") === "true";
    const limit = parseInt(searchParams.get("limit") || "100", 10);

    const workspaceId = await getCurrentWorkspaceId();
    if (!workspaceId) {
      return NextResponse.json({ error: "No workspace found" }, { status: 400 });
    }

    // If daily workflow, use the function
    if (dailyWorkflow) {
      const { data: workflowData, error: workflowError } = await supabase
        .rpc('get_daily_workflow_tasks', {
          p_workspace_id: workspaceId,
          p_user_id: assignedTo === "me" ? user.id : null
        });

      if (workflowError) {
        return NextResponse.json({ error: workflowError.message }, { status: 500 });
      }

      return NextResponse.json({
        data: workflowData,
        grouped: {
          critical: workflowData?.find((g: any) => g.priority_level === 'critical')?.tasks || [],
          high: workflowData?.find((g: any) => g.priority_level === 'high')?.tasks || [],
          medium: workflowData?.find((g: any) => g.priority_level === 'medium')?.tasks || [],
          low: workflowData?.find((g: any) => g.priority_level === 'low')?.tasks || [],
        }
      });
    }

    // Build query
    let query = supabase
      .from("tasks_v3")
      .select(`
        *,
        contacts:contact_id (
          id,
          first_name,
          last_name,
          email
        )
      `)
      .eq("workspace_id", workspaceId)
      .order("priority_score", { ascending: false, nullsLast: true })
      .order("due_at", { ascending: true })
      .limit(limit);

    // Filter by status
    if (status !== "all") {
      query = query.eq("status", status);
    }

    // Filter by priority
    if (priority && priority !== "all") {
      query = query.eq("priority", priority);
    }

    // Filter by task type
    if (taskType) {
      query = query.eq("task_type", taskType);
    }

    // Filter by assignee
    if (assignedTo === "me") {
      query = query.eq("user_id", user.id);
    } else if (assignedTo && assignedTo !== "all") {
      query = query.eq("user_id", assignedTo);
    }

    // Filter by contact
    if (contactId) {
      query = query.eq("contact_id", contactId);
    }

    // Filter by lead
    if (leadId) {
      query = query.eq("lead_id", leadId);
    }

    // Filter overdue
    if (overdue) {
      query = query.lt("due_at", new Date().toISOString()).eq("status", "open");
    }

    const { data: tasks, error } = await query;

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    // Transform to API format
    const transformed: TaskV3[] = (tasks || []).map((t: any) => ({
      id: t.id,
      workspaceId: t.workspace_id,
      userId: t.user_id || undefined,
      contactId: t.contact_id || undefined,
      leadId: t.lead_id || undefined,
      taskType: t.task_type,
      priority: t.priority,
      status: t.status,
      title: t.title,
      description: t.description || undefined,
      notes: t.notes || undefined,
      dueAt: t.due_at,
      dueDate: t.due_date || undefined,
      completedAt: t.completed_at || undefined,
      priorityScore: t.priority_score || undefined,
      metadata: t.metadata || {},
      autoGenerated: t.auto_generated || false,
      autoSource: t.auto_source || undefined,
      parentTaskId: t.parent_task_id || undefined,
      nextTaskId: t.next_task_id || undefined,
      chainPosition: t.chain_position || undefined,
      isRecurrent: t.is_recurrent || false,
      recurrencePattern: t.recurrence_pattern || undefined,
      recurrenceConfig: t.recurrence_config || undefined,
      nextRecurrenceAt: t.next_recurrence_at || undefined,
      pipelineStageId: t.pipeline_stage_id || undefined,
      suggestedNextStage: t.suggested_next_stage || undefined,
      createdAt: t.created_at,
      updatedAt: t.updated_at,
      createdBy: t.created_by || undefined,
    }));

    // Group by priority for dashboard
    const grouped = {
      critical: transformed.filter(t => t.priority === 'critical' && t.status === 'open'),
      high: transformed.filter(t => t.priority === 'high' && t.status === 'open'),
      medium: transformed.filter(t => t.priority === 'medium' && t.status === 'open'),
      low: transformed.filter(t => t.priority === 'low' && t.status === 'open'),
      overdue: transformed.filter(t => t.status === 'overdue' || (t.status === 'open' && new Date(t.dueAt) < new Date())),
      completed: transformed.filter(t => t.status === 'completed'),
    };

    // Get stats
    const stats = {
      critical: grouped.critical.length,
      high: grouped.high.length,
      medium: grouped.medium.length,
      low: grouped.low.length,
      overdue: grouped.overdue.length,
      completed: grouped.completed.length,
      total: transformed.length,
    };

    return NextResponse.json({
      data: transformed,
      grouped,
      stats,
    });
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}

/**
 * POST /api/tasks/v3
 * Create a new task (v3)
 */
export async function POST(req: NextRequest) {
  try {
    const supabase = createSupabaseServer();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = (await req.json()) as CreateTaskInputV3;

    // Validate required fields
    if (!body.title || !body.dueAt || !body.taskType) {
      return NextResponse.json(
        { error: "Missing required fields: title, dueAt, taskType" },
        { status: 400 }
      );
    }

    const workspaceId = await getCurrentWorkspaceId();
    if (!workspaceId) {
      return NextResponse.json({ error: "No workspace found" }, { status: 400 });
    }

    // Create task
    const { data: task, error } = await supabase
      .from("tasks_v3")
      .insert({
        workspace_id: workspaceId,
        user_id: body.userId || user.id,
        contact_id: body.contactId || null,
        lead_id: body.leadId || null,
        task_type: body.taskType,
        priority: body.priority || 'medium',
        status: 'open',
        title: body.title,
        description: body.description || null,
        notes: body.notes || null,
        due_at: body.dueAt,
        auto_generated: false,
        metadata: body.metadata || {},
        is_recurrent: body.isRecurrent || false,
        recurrence_pattern: body.recurrencePattern || null,
        recurrence_config: body.recurrenceConfig || null,
        pipeline_stage_id: body.pipelineStageId || null,
        suggested_next_stage: body.suggestedNextStage || null,
        created_by: user.id,
      })
      .select("*")
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    // Calculate priority score
    await supabase.rpc('calculate_task_priority_score', {
      p_task_id: task.id
    });

    // Transform to API format
    const transformed: TaskV3 = {
      id: task.id,
      workspaceId: task.workspace_id,
      userId: task.user_id || undefined,
      contactId: task.contact_id || undefined,
      leadId: task.lead_id || undefined,
      taskType: task.task_type,
      priority: task.priority,
      status: task.status,
      title: task.title,
      description: task.description || undefined,
      notes: task.notes || undefined,
      dueAt: task.due_at,
      dueDate: task.due_date || undefined,
      priorityScore: task.priority_score || undefined,
      metadata: task.metadata || {},
      autoGenerated: task.auto_generated || false,
      autoSource: task.auto_source || undefined,
      isRecurrent: task.is_recurrent || false,
      recurrencePattern: task.recurrence_pattern || undefined,
      recurrenceConfig: task.recurrence_config || undefined,
      pipelineStageId: task.pipeline_stage_id || undefined,
      suggestedNextStage: task.suggested_next_stage || undefined,
      createdAt: task.created_at,
      updatedAt: task.updated_at,
      createdBy: task.created_by || undefined,
    };

    return NextResponse.json({ data: transformed }, { status: 201 });
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}





















































