import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServer } from "@/lib/supabaseServer";
import { getCurrentOrgId } from "@/lib/org-helpers";
import { logTaskCreated, logTaskAssigned } from "@/lib/contactActivity";
import { logTaskCreatedV3 } from "@/lib/contactActivityV3";

export type Task = {
  id: string;
  orgId: string;
  contactId?: string;
  leadId?: string; // Roofing-specific: reference to lead
  replyThreadId?: string;
  campaignId?: string;
  assignedTo?: string;
  title: string;
  description?: string; // Roofing-specific: task description
  notes?: string;
  dueAt: string;
  dueDate?: string;
  priority: 'low' | 'medium' | 'high';
  status: 'open' | 'completed';
  completed: boolean;
  completedAt?: string;
  createdAt: string;
  updatedAt: string;
  autoGenerated: boolean;
  autoType?: string;
  createdBy?: string;
  type?: 'call' | 'text' | 'email' | 'inspection' | 'follow_up' | 'send_estimate' | 're_engage' | 'answer_question' | 'review_damage' | 'insurance_support';
};

export type CreateTaskInput = {
  contactId?: string;
  leadId?: string; // Roofing-specific
  replyThreadId?: string;
  campaignId?: string;
  title: string;
  description?: string; // Roofing-specific
  dueAt: string;
  assignedTo?: string;
  notes?: string;
  priority?: 'low' | 'medium' | 'high';
  type?: 'call' | 'text' | 'email' | 'inspection' | 'follow_up' | 'send_estimate' | 're_engage' | 'answer_question' | 'review_damage' | 'insurance_support';
};

/**
 * GET /api/tasks
 * Query params:
 * - status: 'open' | 'completed' | 'all' (default: 'open')
 * - assignedTo: 'me' | 'all' (default: 'me')
 * - dateRange: 'today' | 'week' | 'all' (default: 'all')
 * - limit: number (default: 100)
 * - cursor: string (for pagination)
 */
export async function GET(req: NextRequest) {
  try {
    const supabase = createSupabaseServer();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const searchParams = req.nextUrl.searchParams;
    const status = searchParams.get("status") || "open";
    const assignedTo = searchParams.get("assignedTo") || "all";
    const dateRange = searchParams.get("dateRange") || "all";
    const priority = searchParams.get("priority");
    const contactId = searchParams.get("contactId");
    const leadId = searchParams.get("leadId"); // Roofing-specific
    const campaignId = searchParams.get("campaignId");
    const taskType = searchParams.get("type"); // Roofing-specific: callback, appointment, quote_followup
    const due = searchParams.get("due"); // 'today' | 'overdue'
    const teamId = searchParams.get("team_id"); // Block 25220: Filter by team
    const limit = parseInt(searchParams.get("limit") || "100", 10);
    const cursor = searchParams.get("cursor");

    // Get current org_id
    const orgId = await getCurrentOrgId();
    if (!orgId) {
      return NextResponse.json({ error: "No organization found" }, { status: 400 });
    }

    // Build query
    let query = supabase
      .from("tasks")
      .select("*")
      .eq("org_id", orgId)
      .order("due_at", { ascending: true })
      .limit(limit);

    // Block 25220: Filter by team if specified
    if (teamId) {
      // Get team's task categories
      const { data: teamCategories } = await supabase
        .from("team_task_categories")
        .select("task_categories")
        .eq("team_id", teamId)
        .single();

      if (teamCategories && teamCategories.task_categories.length > 0) {
        // Filter tasks by team's categories (if task has a category field)
        // For now, we'll filter by assigned_team_id if it exists
        query = query.eq("assigned_team_id", teamId);
      } else {
        // If team has no specific categories, filter by team members
        const { data: teamMembers } = await supabase
          .from("team_members")
          .select("user_id")
          .eq("team_id", teamId)
          .eq("is_active", true);

        if (teamMembers && teamMembers.length > 0) {
          const userIds = teamMembers.map((m) => m.user_id);
          query = query.in("assigned_to", userIds);
        } else {
          // No team members, return empty
          return NextResponse.json({
            data: [],
            grouped: {
              overdue: [],
              today: [],
              tomorrow: [],
              thisWeek: [],
              later: [],
            },
            pagination: { cursor: null, limit, hasMore: false },
          });
        }
      }
    }

    // Filter by status (open/completed)
    if (status === "open") {
      query = query.eq("status", "open").eq("completed", false);
    } else if (status === "completed") {
      query = query.eq("status", "completed").eq("completed", true);
    }

    // Filter by assignee
    if (assignedTo === "me") {
      query = query.eq("assigned_to", user.id);
    } else if (assignedTo && assignedTo !== "all") {
      query = query.eq("assigned_to", assignedTo);
    }

    // Filter by priority
    if (priority && ['low', 'medium', 'high'].includes(priority)) {
      query = query.eq("priority", priority);
    }

    // Filter by contact
    if (contactId) {
      query = query.eq("contact_id", contactId);
    }

    // Filter by lead (roofing-specific)
    if (leadId) {
      query = query.eq("lead_id", leadId);
    }

    // Filter by campaign
    if (campaignId) {
      query = query.eq("campaign_id", campaignId);
    }

    // Filter by task type
    if (taskType && ['call', 'text', 'email', 'inspection', 'follow_up', 'send_estimate', 're_engage', 'answer_question', 'review_damage', 'insurance_support'].includes(taskType)) {
      query = query.eq("type", taskType);
    }

    // Filter by due date
    const now = new Date();
    if (due === "today") {
      const startOfDay = new Date(now.setHours(0, 0, 0, 0));
      const endOfDay = new Date(now.setHours(23, 59, 59, 999));
      query = query.gte("due_at", startOfDay.toISOString()).lte("due_at", endOfDay.toISOString());
    } else if (due === "overdue") {
      query = query.lt("due_at", now.toISOString()).eq("completed", false);
    } else if (dateRange === "today") {
      const startOfDay = new Date(now.setHours(0, 0, 0, 0));
      const endOfDay = new Date(now.setHours(23, 59, 59, 999));
      query = query.gte("due_at", startOfDay.toISOString()).lte("due_at", endOfDay.toISOString());
    } else if (dateRange === "week") {
      const startOfWeek = new Date(now.setDate(now.getDate() - now.getDay()));
      startOfWeek.setHours(0, 0, 0, 0);
      const endOfWeek = new Date(startOfWeek);
      endOfWeek.setDate(startOfWeek.getDate() + 7);
      query = query.gte("due_at", startOfWeek.toISOString()).lt("due_at", endOfWeek.toISOString());
    }

    // Cursor-based pagination
    if (cursor) {
      query = query.gt("due_at", cursor);
    }

    const { data: tasks, error } = await query;

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    // Transform to API format
    const transformed: Task[] = (tasks || []).map((t: any) => ({
      id: t.id,
      orgId: t.org_id,
      contactId: t.contact_id || undefined,
      leadId: t.lead_id || undefined, // Roofing-specific
      replyThreadId: t.reply_thread_id || undefined,
      campaignId: t.campaign_id || undefined,
      assignedTo: t.assigned_to || undefined,
      title: t.title,
      description: t.description || undefined, // Roofing-specific
      notes: t.notes || undefined,
      dueAt: t.due_at,
      dueDate: t.due_date || undefined,
      priority: t.priority || 'normal',
      status: t.status || (t.completed ? 'completed' : 'open'),
      completed: t.completed,
      completedAt: t.completed_at || undefined,
      createdAt: t.created_at,
      updatedAt: t.updated_at,
      autoGenerated: t.auto_generated,
      autoType: t.auto_type || undefined,
      createdBy: t.created_by || undefined,
      type: t.type || undefined, // Roofing-specific
    }));

    // Group tasks by date buckets
    const grouped = {
      overdue: [] as Task[],
      today: [] as Task[],
      tomorrow: [] as Task[],
      thisWeek: [] as Task[],
      later: [] as Task[],
    };

    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);
    const endOfWeek = new Date(today);
    endOfWeek.setDate(today.getDate() + (7 - today.getDay()));

    transformed.forEach((task) => {
      if (task.completed) return; // Skip completed tasks in grouping

      const dueDate = new Date(task.dueAt);
      dueDate.setHours(0, 0, 0, 0);

      if (dueDate < today) {
        grouped.overdue.push(task);
      } else if (dueDate.getTime() === today.getTime()) {
        grouped.today.push(task);
      } else if (dueDate.getTime() === tomorrow.getTime()) {
        grouped.tomorrow.push(task);
      } else if (dueDate <= endOfWeek) {
        grouped.thisWeek.push(task);
      } else {
        grouped.later.push(task);
      }
    });

    // Determine if there are more results
    const hasMore = tasks && tasks.length === limit;

    return NextResponse.json({
      data: transformed,
      grouped,
      pagination: {
        cursor: hasMore && transformed.length > 0 
          ? transformed[transformed.length - 1].dueAt 
          : null,
        limit,
        hasMore: !!hasMore,
      },
    });
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}

/**
 * POST /api/tasks
 * Body: CreateTaskInput
 */
export async function POST(req: NextRequest) {
  try {
    const supabase = createSupabaseServer();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = (await req.json()) as CreateTaskInput;

    // Validate required fields
    if (!body.title || !body.dueAt) {
      return NextResponse.json(
        { error: "Missing required fields: title, dueAt" },
        { status: 400 }
      );
    }

    // Get current org_id
    const orgId = await getCurrentOrgId();
    if (!orgId) {
      return NextResponse.json({ error: "No organization found" }, { status: 400 });
    }

    // Create task
    const { data: task, error } = await supabase
      .from("tasks")
      .insert({
        org_id: orgId,
        contact_id: body.contactId || null,
        lead_id: body.leadId || null, // Roofing-specific
        reply_thread_id: body.replyThreadId || null,
        campaign_id: body.campaignId || null,
        assigned_to: body.assignedTo || user.id, // Default to creator if not assigned
        title: body.title,
        description: body.description || null, // Roofing-specific
        notes: body.notes || null,
        due_at: body.dueAt,
        priority: body.priority || 'medium',
        type: body.type || 'follow_up',
        status: 'open',
        completed: false,
        auto_generated: false,
        created_by: user.id,
      })
      .select("*")
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    // Log activity timeline event
    if (task.contact_id) {
      try {
        // Log to v2 activity_events table (existing)
        await logTaskCreated(orgId, task.contact_id, {
          taskId: task.id,
          title: task.title,
          dueDate: task.due_at,
          assignedTo: task.assigned_to || undefined,
          userId: user.id,
        });

        // Log assignment if assigned
        if (task.assigned_to && task.assigned_to !== user.id) {
          await logTaskAssigned(orgId, task.contact_id, {
            taskId: task.id,
            title: task.title,
            assignedTo: task.assigned_to,
          });
        }

        // Block 16000: Log to v3 contact_activity table
        const { logTaskCreated } = await import("@/lib/contactActivityV3");
        await logTaskCreated(supabase, {
          contactId: task.contact_id,
          workspaceId: orgId, // orgId is workspace_id in this context
          taskId: task.id,
          taskTitle: task.title,
          createdBy: user.id,
        }).catch((err) => {
          console.error("Failed to log task creation:", err);
        });
      } catch (err) {
        console.error("Error logging task activity:", err);
        // Don't fail the request if logging fails
      }
    }

    // Create notification if task is assigned to someone else
    if (task.assigned_to && task.assigned_to !== user.id) {
      try {
        await supabase.rpc("create_task_assigned_notification", {
          p_org_id: orgId,
          p_user_id: task.assigned_to,
          p_task_id: task.id,
          p_contact_id: task.contact_id,
        });
      } catch (err) {
        console.error("Error creating notification:", err);
        // Don't fail the request if notification creation fails
      }
    }

    // Transform to API format
    const transformed: Task = {
      id: task.id,
      orgId: task.org_id,
      contactId: task.contact_id || undefined,
      leadId: task.lead_id || undefined, // Roofing-specific
      replyThreadId: task.reply_thread_id || undefined,
      campaignId: task.campaign_id || undefined,
      assignedTo: task.assigned_to || undefined,
      title: task.title,
      description: task.description || undefined, // Roofing-specific
      notes: task.notes || undefined,
      dueAt: task.due_at,
      dueDate: task.due_date || undefined,
      priority: task.priority || 'medium',
      status: task.status || (task.completed ? 'completed' : 'open'),
      completed: task.completed,
      completedAt: task.completed_at || undefined,
      createdAt: task.created_at,
      updatedAt: task.updated_at,
      autoGenerated: task.auto_generated,
      autoType: task.auto_type || undefined,
      createdBy: task.created_by || undefined,
      type: task.type || undefined, // Roofing-specific
    };

    return NextResponse.json({ data: transformed }, { status: 201 });
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}
