// Block 241000 — SmartSend Roofing Supplier Hub v1
// POST /api/supplier/po/create
// Create a new Purchase Order

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function POST(req: NextRequest) {
  try {
    const supabase = createClient();
    
    // Authenticate user
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json(
        { error: "Unauthorized" },
        { status: 401 }
      );
    }

    const body = await req.json();
    const {
      company_id,
      job_id,
      supplier_id,
      delivery_date,
      delivery_window,
      items, // Array of {material_name, qty, unit, price}
      notes,
    } = body;

    if (!company_id || !supplier_id || !items || !Array.isArray(items) || items.length === 0) {
      return NextResponse.json(
        { error: "company_id, supplier_id, and items array are required" },
        { status: 400 }
      );
    }

    // Create PO (po_number will be auto-generated by trigger)
    const { data: po, error: poError } = await supabase
      .from("purchase_orders")
      .insert({
        company_id,
        job_id: job_id || null,
        supplier_id,
        delivery_date: delivery_date || null,
        delivery_window: delivery_window || 'Any',
        notes: notes || null,
        status: 'pending',
        total_cost: 0, // Will be calculated by trigger
      })
      .select()
      .single();

    if (poError) {
      console.error("PO creation error:", poError);
      return NextResponse.json(
        { error: "Failed to create purchase order" },
        { status: 500 }
      );
    }

    // Create PO items
    const poItems = items.map((item: any) => ({
      po_id: po.id,
      material_name: item.material_name,
      qty: item.qty,
      unit: item.unit || 'pieces',
      price: item.price || 0,
      notes: item.notes || null,
    }));

    const { data: createdItems, error: itemsError } = await supabase
      .from("po_items")
      .insert(poItems)
      .select();

    if (itemsError) {
      console.error("PO items creation error:", itemsError);
      // Delete PO if items failed
      await supabase.from("purchase_orders").delete().eq("id", po.id);
      return NextResponse.json(
        { error: "Failed to create PO items" },
        { status: 500 }
      );
    }

    // Fetch complete PO with items (total_cost will be updated by trigger)
    const { data: completePo, error: fetchError } = await supabase
      .from("purchase_orders")
      .select(`
        *,
        po_items (*),
        suppliers (*),
        jobs:job_id (id, address, homeowner_name)
      `)
      .eq("id", po.id)
      .single();

    if (fetchError) {
      console.error("PO fetch error:", fetchError);
    }

    return NextResponse.json({ 
      po: completePo || po,
      items: createdItems,
    });
  } catch (error: any) {
    console.error("Error in POST /api/supplier/po/create:", error);
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}

























