"use client";

import { useEffect, useMemo, useState } from "react";
import { hasMeetingIntent } from "@/lib/meeting-intent";

type Props = {
  value: string;
  onChange: (v: string) => void;
  recipientEmail?: string;
  triggerText?: string;
};

export default function ComposeSmartAssist({ value, onChange, recipientEmail, triggerText }: Props) {
  const [showCard, setShowCard] = useState(false);
  const calendly = process.env.NEXT_PUBLIC_CALENDLY_URL || "";
  const tz = process.env.ICS_TIMEZONE || "America/Los_Angeles";
  const defaultMin = Number(process.env.NEXT_PUBLIC_ICS_DEFAULT_DURATION_MIN || 15);

  const shouldSuggest = useMemo(() => {
    const source = `${triggerText || ""}\n${value || ""}`;
    return hasMeetingIntent(source);
  }, [value, triggerText]);

  useEffect(() => setShowCard(shouldSuggest), [shouldSuggest]);

  const proposed = useMemo(() => {
    const opts: Date[] = [];
    const now = new Date();
    const base = nextBusinessDay(now);
    opts.push(setTime(base, 10));
    opts.push(setTime(base, 14));
    const nextDay = new Date(base);
    nextDay.setDate(base.getDate() + 1);
    opts.push(setTime(nextDay, 10));
    return opts;
  }, []);

  async function insertCalendlyBlock() {
    const text =
      `Happy to set up a quick call.\n` +
      `Grab a time here: ${calendly}\n`;
    onChange(value ? value + "\n\n" + text : text);
    setShowCard(false);
  }

  async function attachIcs(d: Date) {
    const res = await fetch("/api/ics", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        startISO: d.toISOString(),
        durationMin: defaultMin,
        title: "Intro call",
        description: "Quick intro call (generated by SmartSend)",
        attendeeEmail: recipientEmail,
        mode: "base64",
      }),
    });
    const json = await res.json();
    if (!json?.base64) return alert("Could not generate .ics");
    const href = `data:text/calendar;base64,${json.base64}`;
    const line = `Attached tentative hold (${fmtLocal(d, tz)} • ${defaultMin} min). ICS: ${href}\n`;
    onChange(value ? value + "\n" + line : line);
  }

  if (!showCard) return null;

  return (
    <div className="mt-2 rounded-2xl border p-4 shadow-sm">
      <div className="text-sm font-medium">Suggest: Book a meeting</div>
      <p className="mt-1 text-xs text-gray-600">
        Detected meeting intent. Insert a Calendly block and (optionally) add a prefilled .ics invite.
      </p>
      <div className="mt-3 flex flex-wrap gap-2">
        <button onClick={insertCalendlyBlock} className="rounded-2xl px-3 py-1.5 bg-black text-white text-sm">
          Insert Calendly
        </button>
        {proposed.map((d, i) => (
          <button
            key={i}
            onClick={() => attachIcs(d)}
            className="rounded-2xl px-3 py-1.5 border text-sm"
            title="Attach .ics for this slot"
          >
            .ics {fmtLocal(d, tz)}
          </button>
        ))}
      </div>
    </div>
  );
}

function nextBusinessDay(from: Date) {
  const d = new Date(from);
  d.setDate(d.getDate() + 1);
  let day = d.getDay();
  if (day === 0) d.setDate(d.getDate() + 1);
  if (day === 6) d.setDate(d.getDate() + 2);
  return d;
}

function setTime(d: Date, hour24: number) {
  const x = new Date(d);
  x.setHours(hour24, 0, 0, 0);
  return x;
}

function fmtLocal(d: Date, tz: string) {
  try {
    return new Intl.DateTimeFormat(undefined, {
      timeZone: tz,
      weekday: "short", month: "short", day: "numeric",
      hour: "numeric", minute: "2-digit",
    }).format(d);
  } catch {
    return d.toLocaleString();
  }
}

