// Block 18100 — SmartSend Task System v3
// Task update, complete, and delete endpoints

import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServer } from "@/lib/supabaseServer";
import { getCurrentWorkspaceId } from "@/lib/workspace";
import { TaskV3, TaskPriorityLevel, TaskStatusV3 } from "../route";

/**
 * GET /api/tasks/v3/[id]
 * Get a single task by ID
 */
export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = createSupabaseServer();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const workspaceId = await getCurrentWorkspaceId();
    if (!workspaceId) {
      return NextResponse.json({ error: "No workspace found" }, { status: 400 });
    }

    const { data: task, error } = await supabase
      .from("tasks_v3")
      .select(`
        *,
        contacts:contact_id (
          id,
          first_name,
          last_name,
          email
        ),
        task_events (
          id,
          event_type,
          user_id,
          metadata,
          created_at
        )
      `)
      .eq("id", params.id)
      .eq("workspace_id", workspaceId)
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    if (!task) {
      return NextResponse.json({ error: "Task not found" }, { status: 404 });
    }

    const transformed: TaskV3 = {
      id: task.id,
      workspaceId: task.workspace_id,
      userId: task.user_id || undefined,
      contactId: task.contact_id || undefined,
      leadId: task.lead_id || undefined,
      taskType: task.task_type,
      priority: task.priority,
      status: task.status,
      title: task.title,
      description: task.description || undefined,
      notes: task.notes || undefined,
      dueAt: task.due_at,
      dueDate: task.due_date || undefined,
      completedAt: task.completed_at || undefined,
      priorityScore: task.priority_score || undefined,
      metadata: task.metadata || {},
      autoGenerated: task.auto_generated || false,
      autoSource: task.auto_source || undefined,
      parentTaskId: task.parent_task_id || undefined,
      nextTaskId: task.next_task_id || undefined,
      chainPosition: task.chain_position || undefined,
      isRecurrent: task.is_recurrent || false,
      recurrencePattern: task.recurrence_pattern || undefined,
      recurrenceConfig: task.recurrence_config || undefined,
      nextRecurrenceAt: task.next_recurrence_at || undefined,
      pipelineStageId: task.pipeline_stage_id || undefined,
      suggestedNextStage: task.suggested_next_stage || undefined,
      createdAt: task.created_at,
      updatedAt: task.updated_at,
      createdBy: task.created_by || undefined,
    };

    return NextResponse.json({ data: transformed });
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}

/**
 * PATCH /api/tasks/v3/[id]
 * Update a task
 */
export async function PATCH(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = createSupabaseServer();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const workspaceId = await getCurrentWorkspaceId();
    if (!workspaceId) {
      return NextResponse.json({ error: "No workspace found" }, { status: 400 });
    }

    const body = await req.json();
    const updateData: any = {};

    if (body.title !== undefined) updateData.title = body.title;
    if (body.description !== undefined) updateData.description = body.description;
    if (body.notes !== undefined) updateData.notes = body.notes;
    if (body.dueAt !== undefined) updateData.due_at = body.dueAt;
    if (body.priority !== undefined) updateData.priority = body.priority;
    if (body.status !== undefined) updateData.status = body.status;
    if (body.userId !== undefined) updateData.user_id = body.userId;
    if (body.metadata !== undefined) updateData.metadata = body.metadata;
    if (body.pipelineStageId !== undefined) updateData.pipeline_stage_id = body.pipelineStageId;
    if (body.suggestedNextStage !== undefined) updateData.suggested_next_stage = body.suggestedNextStage;

    // If completing, set completed_at
    if (body.status === 'completed' && !body.completedAt) {
      updateData.completed_at = new Date().toISOString();
    }

    const { data: task, error } = await supabase
      .from("tasks_v3")
      .update(updateData)
      .eq("id", params.id)
      .eq("workspace_id", workspaceId)
      .select("*")
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    // Recalculate priority score if relevant fields changed
    if (body.dueAt !== undefined || body.priority !== undefined || body.metadata !== undefined) {
      await supabase.rpc('calculate_task_priority_score', {
        p_task_id: params.id
      });
    }

    const transformed: TaskV3 = {
      id: task.id,
      workspaceId: task.workspace_id,
      userId: task.user_id || undefined,
      contactId: task.contact_id || undefined,
      leadId: task.lead_id || undefined,
      taskType: task.task_type,
      priority: task.priority,
      status: task.status,
      title: task.title,
      description: task.description || undefined,
      notes: task.notes || undefined,
      dueAt: task.due_at,
      dueDate: task.due_date || undefined,
      completedAt: task.completed_at || undefined,
      priorityScore: task.priority_score || undefined,
      metadata: task.metadata || {},
      autoGenerated: task.auto_generated || false,
      autoSource: task.auto_source || undefined,
      parentTaskId: task.parent_task_id || undefined,
      nextTaskId: task.next_task_id || undefined,
      chainPosition: task.chain_position || undefined,
      isRecurrent: task.is_recurrent || false,
      recurrencePattern: task.recurrence_pattern || undefined,
      recurrenceConfig: task.recurrence_config || undefined,
      nextRecurrenceAt: task.next_recurrence_at || undefined,
      pipelineStageId: task.pipeline_stage_id || undefined,
      suggestedNextStage: task.suggested_next_stage || undefined,
      createdAt: task.created_at,
      updatedAt: task.updated_at,
      createdBy: task.created_by || undefined,
    };

    return NextResponse.json({ data: transformed });
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}

/**
 * DELETE /api/tasks/v3/[id]
 * Delete a task
 */
export async function DELETE(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = createSupabaseServer();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const workspaceId = await getCurrentWorkspaceId();
    if (!workspaceId) {
      return NextResponse.json({ error: "No workspace found" }, { status: 400 });
    }

    const { error } = await supabase
      .from("tasks_v3")
      .delete()
      .eq("id", params.id)
      .eq("workspace_id", workspaceId);

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (error: any) {
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}





















































