import { NextRequest, NextResponse } from "next/server";
import { getSupabaseServer } from "@/lib/supabase/server";
import { detectReplyIntent } from "@/lib/replyIntent";
import { generateIcs } from "@/lib/ics";
import crypto from "crypto";

type InboundPayload = {
  profile_id: string; // who owns the inbox
  contact_id?: string;
  campaign_id?: string;
  raw_text?: string;
  subject?: string;
  from_email?: string;
  message_id_provider?: string;
};

export async function POST(req: NextRequest) {
  const body = (await req.json()) as InboundPayload;
  const sb = getSupabaseServer();

  // 1) Persist the inbound message minimally (assumes messages table exists with RLS on profile_id)
  const { data: msg, error: msgErr } = await sb
    .from("messages")
    .insert({
      profile_id: body.profile_id,
      contact_id: body.contact_id ?? null,
      campaign_id: body.campaign_id ?? null,
      direction: "inbound",
      provider_id: body.message_id_provider ?? null,
      subject: body.subject ?? null,
      body_text: body.raw_text ?? null,
      status: "received",
    })
    .select("*")
    .single();

  if (msgErr) {
    return NextResponse.json({ error: msgErr.message }, { status: 400 });
  }

  const classifyUrl = process.env.NEXT_PUBLIC_BASE_URL
    ? `${process.env.NEXT_PUBLIC_BASE_URL}/api/replies/classify`
    : undefined;

  if (classifyUrl) {
    fetch(classifyUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ message_id: msg.id }),
    }).catch(() => {});
  }

  // 2) Detect intent
  const intent = detectReplyIntent(body.raw_text || "");

  // If not positive, just return the classification for analytics
  if (intent !== "positive_meeting") {
    return NextResponse.json({ intent, message_id: msg.id }, { status: 200 });
  }

  // 3) Create proposed meeting + build an ICS for the *next 3 business days fallback slot*
  const start = nextBusinessSlot();
  const end = new Date(start.getTime() + 30 * 60 * 1000);

  const { data: meeting, error: meetErr } = await sb
    .from("meetings")
    .insert({
      profile_id: body.profile_id,
      contact_id: body.contact_id ?? null,
      campaign_id: body.campaign_id ?? null,
      message_id: msg.id,
      status: "proposed",
      scheduled_at: start,
      notes: "Auto-created from positive reply",
      title: "Intro call",
      location: "Calendly",
    })
    .select("*")
    .single();

  if (meetErr) {
    return NextResponse.json({ error: meetErr.message }, { status: 400 });
  }

  // 4) Prepare signed ICS blob (download URL the sender can attach or link)
  const ics = generateIcs({
    summary: "Intro call",
    description:
      "Proposed intro call generated by SmartSendAI. If this time doesn't work, please pick a slot via Calendly.",
    start,
    end,
    url: process.env.NEXT_PUBLIC_CALENDLY_PUBLIC_LINK, // e.g., https://calendly.com/yourname/intro
    organizerEmail: process.env.NEXT_PUBLIC_OUTBOUND_FROM_EMAIL,
    attendeeEmail: body.from_email,
  });

  // Hash to create a simple signed token
  const token = signToken(meeting.id);

  // Store ICS in a signed URL table or return raw. For speed, return raw + a signed GET endpoint.
  const icsUrl = `${process.env.NEXT_PUBLIC_BASE_URL}/api/meetings/${meeting.id}/ics?token=${token}`;

  return NextResponse.json(
    {
      intent,
      message_id: msg.id,
      meeting_id: meeting.id,
      calendly_link: process.env.NEXT_PUBLIC_CALENDLY_PUBLIC_LINK,
      ics_download_url: icsUrl,
      // Optional: raw_ics if your mailer wants to attach directly
      ics,
    },
    { status: 200 }
  );
}

function nextBusinessSlot() {
  // Next day at 11:00 local as placeholder
  const d = new Date();
  d.setDate(d.getDate() + 1);
  d.setHours(11, 0, 0, 0);
  // Skip Saturday/Sunday
  const day = d.getDay();
  if (day === 0) d.setDate(d.getDate() + 1); // Sunday -> Monday
  if (day === 6) d.setDate(d.getDate() + 2); // Saturday -> Monday
  return d;
}

function signToken(meetingId: string) {
  const secret = process.env.MEETING_ICS_SIGNING_SECRET || "dev-secret";
  return crypto.createHmac("sha256", secret).update(meetingId).digest("hex");
} 