-- Template variants system for A/B testing
-- File: supabase/migrations/20250217000000_create_template_variants.sql

-- Base template per campaign
create table if not exists campaign_templates (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references campaigns(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Default',
  subject text not null,
  body_html text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Variants generated by AI
create table if not exists template_variants (
  id uuid primary key default gen_random_uuid(),
  campaign_template_id uuid not null references campaign_templates(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null,                   -- e.g. "V1: Curious hook"
  subject text not null,
  body_html text not null,
  weight int not null default 50,        -- % for splitting (sum normalized per campaign)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add template_variant_id to email_logs if the table exists
do $$
begin
  if exists (select from information_schema.tables where table_name = 'email_logs') then
    alter table email_logs add column if not exists template_variant_id uuid references template_variants(id);
  end if;
end $$;

-- Variant roll-up metrics view
create or replace view variant_metrics as
select
  tv.id as variant_id,
  tv.label,
  tv.weight,
  ct.campaign_id,
  count(el.id)::int as sent,
  sum((el.opened_at is not null)::int)::int as opens,
  sum((el.clicked_at is not null)::int)::int as clicks,
  sum((el.replied_at is not null)::int)::int as replies,
  round(100.0 * sum((el.opened_at is not null)::int) / nullif(count(el.id),0), 2) as open_rate,
  round(100.0 * sum((el.clicked_at is not null)::int) / nullif(count(el.id),0), 2) as click_rate,
  round(100.0 * sum((el.replied_at is not null)::int) / nullif(count(el.id),0), 2) as reply_rate
from template_variants tv
join campaign_templates ct on ct.id = tv.campaign_template_id
left join email_logs el on el.template_variant_id = tv.id
group by tv.id, tv.label, tv.weight, ct.campaign_id;

-- Add indexes
create index if not exists idx_campaign_templates_campaign_id on campaign_templates(campaign_id);
create index if not exists idx_campaign_templates_user_id on campaign_templates(user_id);
create index if not exists idx_template_variants_template_id on template_variants(campaign_template_id);
create index if not exists idx_template_variants_user_id on template_variants(user_id);
create index if not exists idx_email_logs_variant_id on email_logs(template_variant_id) where template_variant_id is not null;

-- RLS policies
alter table campaign_templates enable row level security;
alter table template_variants enable row level security;

-- Users can only manage their own templates
create policy "Users can view own templates"
  on campaign_templates for select
  using (auth.uid() = user_id);

create policy "Users can insert own templates"
  on campaign_templates for insert
  with check (auth.uid() = user_id);

create policy "Users can update own templates"
  on campaign_templates for update
  using (auth.uid() = user_id);

create policy "Users can delete own templates"
  on campaign_templates for delete
  using (auth.uid() = user_id);

-- Variants policies
create policy "Users can view own variants"
  on template_variants for select
  using (auth.uid() = user_id);

create policy "Users can insert own variants"
  on template_variants for insert
  with check (auth.uid() = user_id);

create policy "Users can update own variants"
  on template_variants for update
  using (auth.uid() = user_id);

create policy "Users can delete own variants"
  on template_variants for delete
  using (auth.uid() = user_id);

-- Optional: Helper view to pick winners
create or replace view variant_winners as
select campaign_id, variant_id, label, reply_rate, sent
from (
  select 
    vm.*, 
    row_number() over (partition by vm.campaign_id order by vm.reply_rate desc nulls last, vm.sent desc) as rk
  from variant_metrics vm
) x
where rk = 1 and sent >= 50; -- only if enough volume