-- =========================================================
-- Block 21900 — SmartSend Roofing Action Queue v1
-- ("Do This Next" List for Owners & Estimators — Zero Guesswork, All Money)
-- =========================================================
-- 
-- This turns all the intelligence we built (Heat Score, Job Probability, 
-- Risk Engine, Missed Opportunity Detector, Pipeline Board, Resurrection Engine, 
-- Coaching Engine) into simple, brutal execution.
--
-- Every estimator and owner gets a live, prioritized queue of tasks:
-- - Call this homeowner
-- - Send this proposal
-- - Follow up on this high-probability job
-- - Save this critical-risk lead
-- - Book this estimate
-- - Answer this angry homeowner
-- - Revive this ghosted lead
--
-- The Action Queue is:
-- - Sorted by money impact + urgency
-- - Auto-generated by SmartSend
-- - Clears as the team executes
-- - This is direct revenue execution.

-- ============================================================================
-- 1. CREATE action_queue_tasks TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.action_queue_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  
  lead_id UUID NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  assigned_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL, -- estimator or owner
  
  task_type TEXT NOT NULL CHECK (task_type IN (
    'call_homeowner',
    'send_proposal',
    'follow_up_hot',
    'follow_up_warm',
    'save_critical_risk_job',
    'reply_to_angry_homeowner',
    'book_estimate',
    'review_stuck_job',
    'owner_review_high_value',
    'resurrection_follow_up'
  )),
  
  priority INTEGER NOT NULL CHECK (priority >= 1 AND priority <= 100), -- 1 = highest, 100 = lowest
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'done', 'skipped')),
  
  due_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  
  source TEXT,        -- e.g. 'risk_engine', 'heat_engine', 'command_center', 'manual'
  metadata JSONB DEFAULT '{}'::jsonb  -- any extra context (reason, suggested message, etc.)
);

-- ============================================================================
-- 2. CREATE INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_action_queue_workspace_user_status 
  ON public.action_queue_tasks (workspace_id, assigned_user_id, status);

CREATE INDEX IF NOT EXISTS idx_action_queue_lead_id 
  ON public.action_queue_tasks (lead_id);

CREATE INDEX IF NOT EXISTS idx_action_queue_priority_status 
  ON public.action_queue_tasks (priority ASC, status) 
  WHERE status = 'open';

CREATE INDEX IF NOT EXISTS idx_action_queue_due_at 
  ON public.action_queue_tasks (due_at) 
  WHERE status = 'open' AND due_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_action_queue_task_type 
  ON public.action_queue_tasks (task_type, status) 
  WHERE status = 'open';

-- Unique constraint: one open task per lead + task_type + assigned_user_id
CREATE UNIQUE INDEX IF NOT EXISTS idx_action_queue_unique_open_task
  ON public.action_queue_tasks (lead_id, task_type, assigned_user_id)
  WHERE status = 'open';

-- ============================================================================
-- 3. ENABLE ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.action_queue_tasks ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view tasks in their workspace
CREATE POLICY "Users can view tasks in their workspace"
  ON public.action_queue_tasks
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.workspace_members wm
      WHERE wm.workspace_id = action_queue_tasks.workspace_id
        AND wm.user_id = auth.uid()
    )
  );

-- Policy: Users can insert tasks in their workspace
CREATE POLICY "Users can insert tasks in their workspace"
  ON public.action_queue_tasks
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.workspace_members wm
      WHERE wm.workspace_id = action_queue_tasks.workspace_id
        AND wm.user_id = auth.uid()
    )
  );

-- Policy: Users can update tasks in their workspace
CREATE POLICY "Users can update tasks in their workspace"
  ON public.action_queue_tasks
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.workspace_members wm
      WHERE wm.workspace_id = action_queue_tasks.workspace_id
        AND wm.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.workspace_members wm
      WHERE wm.workspace_id = action_queue_tasks.workspace_id
        AND wm.user_id = auth.uid()
    )
  );

-- Policy: Service role has full access
CREATE POLICY "Service role has full access"
  ON public.action_queue_tasks
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================================================
-- 4. COMMENTS FOR DOCUMENTATION
-- ============================================================================

COMMENT ON TABLE public.action_queue_tasks IS 'Block 21900: Action Queue tasks for estimators and owners. Prioritized list of next best actions based on heat score, job probability, risk, etc.';
COMMENT ON COLUMN public.action_queue_tasks.task_type IS 'Block 21900: Type of task: call_homeowner, send_proposal, follow_up_hot, follow_up_warm, save_critical_risk_job, reply_to_angry_homeowner, book_estimate, review_stuck_job, owner_review_high_value, resurrection_follow_up';
COMMENT ON COLUMN public.action_queue_tasks.priority IS 'Block 21900: Priority score (1-100). Lower number = higher priority. Calculated from heat_score, job_probability, risk_category, etc.';
COMMENT ON COLUMN public.action_queue_tasks.status IS 'Block 21900: Task status: open, in_progress, done, skipped';
COMMENT ON COLUMN public.action_queue_tasks.source IS 'Block 21900: Source that generated this task: risk_engine, heat_engine, command_center, manual, etc.';
COMMENT ON COLUMN public.action_queue_tasks.metadata IS 'Block 21900: Additional context: reason, suggested message, risk_score, etc.';









































