-- Block 478 — Predictive SDR Actions ("Next Best Move")
-- Every thread gets a Next Best Action generated by AI — what an elite SDR would do next

-- ============================================================================
-- 1️⃣ Add NBM columns to ai_sdr_threads
-- ============================================================================

alter table public.ai_sdr_threads
  add column if not exists next_best_action text,                    -- short label, e.g. 'send_followup'
  add column if not exists next_best_action_reason text,             -- short explanation
  add column if not exists next_best_action_generated_at timestamptz,
  add column if not exists next_best_action_options jsonb;           -- list of ranked options

-- Indexes for efficient queries
create index if not exists idx_ai_sdr_threads_nbm_action on public.ai_sdr_threads(next_best_action);
create index if not exists idx_ai_sdr_threads_nbm_generated on public.ai_sdr_threads(next_best_action_generated_at);
create index if not exists idx_ai_sdr_threads_nbm_stale on public.ai_sdr_threads(last_message_at, next_best_action_generated_at) 
  where next_best_action_generated_at is not null;

-- ============================================================================
-- 2️⃣ Update ai_sdr_thread_overview view to include NBM columns
-- ============================================================================

create or replace view ai_sdr_thread_overview as
select
  t.id as thread_id,
  t.lead_id,
  t.campaign_id,
  t.status,
  t.last_message_from,
  t.last_message_at,
  t.next_action_at,

  t.summary,
  t.summary_updated_at,
  t.health_score,
  t.health_label,
  t.auto_summary_enabled,

  t.next_best_action,
  t.next_best_action_reason,
  t.next_best_action_generated_at,
  t.next_best_action_options,

  l.email as lead_email,
  coalesce(l.first_name || ' ' || l.last_name, l.first_name, l.last_name, l.email) as lead_name,
  c.name as campaign_name,

  (
    select e.event_type
    from ai_sdr_events e
    where e.thread_id = t.id
    order by e.created_at desc
    limit 1
  ) as last_ai_event_type,
  (
    select e.created_at
    from ai_sdr_events e
    where e.thread_id = t.id
    order by e.created_at desc
    limit 1
  ) as last_ai_event_at

from ai_sdr_threads t
join leads l on l.id = t.lead_id
left join campaigns c on c.id = t.campaign_id;

comment on view ai_sdr_thread_overview is 'Overview of AI SDR threads with lead, campaign, summary, health score, and next best action info for list page';


