-- ============================================================
-- Block 257900 — SmartSend AI Executive Brain v1
-- Owner Daily Briefings • Business Health Score • Strategic Alerts
-- Recommendations • Executive Dashboard • Cash Flow Forecast
-- ============================================================
--
-- This block turns SmartSend into the CEO-level intelligence layer
-- for roofing companies.
--
-- It sits on top of the multi-company schema (Block 25820) and
-- converts raw company data into:
--  - Daily Owner Briefings
--  - 0–100 Business Health Scores
--  - Strategic Alerts (risks & opportunities)
--  - Concrete AI Recommendations
--  - Wins / Problems summaries
--  - Executive dashboard metrics
--  - Weekly cash flow outlook
--
-- This migration defines the persistent storage for:
--  - Historical health scores
--  - Logged alerts
--  - Logged recommendations
-- ============================================================

-- =====================================================================
-- PART 1 — EXECUTIVE HEALTH SCORES TABLE
-- =====================================================================
-- Stores daily business health scores per roofing company

CREATE TABLE IF NOT EXISTS public.executive_health_scores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Company context (multi-company engine)
  roofing_company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,

  -- Overall 0–100 health score for the business
  overall_score numeric(5,2) NOT NULL CHECK (overall_score >= 0 AND overall_score <= 100),

  -- Per-dimension breakdown (JSONB)
  -- Example:
  --   {
  --     "sales": 82,
  --     "production": 76,
  --     "finances": 71,
  --     "reputation": 90,
  --     "staffing": 68
  --   }
  categories jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Snapshot date (one score per company per day)
  snapshot_date date NOT NULL DEFAULT CURRENT_DATE,

  -- Optional details / explanation of score
  notes text,

  created_at timestamptz NOT NULL DEFAULT now()
);

-- Ensure only one score per company per day
CREATE UNIQUE INDEX IF NOT EXISTS idx_executive_health_scores_unique_company_day
  ON public.executive_health_scores(roofing_company_id, snapshot_date);

CREATE INDEX IF NOT EXISTS idx_executive_health_scores_company_date
  ON public.executive_health_scores(roofing_company_id, created_at DESC);


-- =====================================================================
-- PART 2 — EXECUTIVE ALERTS TABLE
-- =====================================================================
-- Instant red flags and opportunity alerts for owners

CREATE TABLE IF NOT EXISTS public.executive_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  roofing_company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,

  -- High-level category for the alert
  -- Examples: 'risk', 'opportunity', 'financial', 'staffing', 'production', 'reputation'
  alert_type text NOT NULL,

  -- Human-readable alert message
  message text NOT NULL,

  -- low / medium / high / critical
  severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),

  -- Optional structured payload with underlying metrics
  -- Example: { "job_id": "...", "margin": 0.21, "target_margin": 0.30 }
  context jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Has the owner/admin acknowledged this alert?
  acknowledged boolean NOT NULL DEFAULT false,
  acknowledged_at timestamptz,

  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_executive_alerts_company_created
  ON public.executive_alerts(roofing_company_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_executive_alerts_company_severity
  ON public.executive_alerts(roofing_company_id, severity, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_executive_alerts_unacked
  ON public.executive_alerts(roofing_company_id, acknowledged, created_at DESC)
  WHERE acknowledged = false;


-- =====================================================================
-- PART 3 — EXECUTIVE RECOMMENDATIONS TABLE
-- =====================================================================
-- Concrete owner-level action items generated by the Executive Brain

CREATE TABLE IF NOT EXISTS public.executive_recommendations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  roofing_company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,

  -- Freeform recommendation text (owner-facing language)
  recommendation text NOT NULL,

  -- Category to help organize the inbox of actions
  -- Examples: 'sales', 'production', 'finance', 'staffing', 'customer_experience', 'scheduling', 'collections'
  category text NOT NULL,

  -- Optional JSON describing the underlying data or links
  context jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Target date this recommendation applies to (defaults to today)
  target_date date NOT NULL DEFAULT CURRENT_DATE,

  -- Has the owner marked this as done / handled?
  completed boolean NOT NULL DEFAULT false,
  completed_at timestamptz,

  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_executive_recommendations_company_date
  ON public.executive_recommendations(roofing_company_id, target_date DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_executive_recommendations_company_completed
  ON public.executive_recommendations(roofing_company_id, completed, target_date DESC)
  WHERE completed = false;


-- =====================================================================
-- PART 4 — ROW LEVEL SECURITY (RLS)
-- =====================================================================
-- We piggyback on Block 25820's is_company_member() helper.
-- Only members of a roofing company can see its executive intelligence.

-- Enable RLS
ALTER TABLE public.executive_health_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.executive_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.executive_recommendations ENABLE ROW LEVEL SECURITY;

-- Helper function must already exist from Block 25820:
--   public.is_company_member(check_company_id uuid) RETURNS boolean

-- Health scores policies
CREATE POLICY "exec_health_scores_company_members_select"
  ON public.executive_health_scores
  FOR SELECT
  USING (public.is_company_member(roofing_company_id));

CREATE POLICY "exec_health_scores_company_members_insert"
  ON public.executive_health_scores
  FOR INSERT
  WITH CHECK (public.is_company_member(roofing_company_id));

-- Alerts policies
CREATE POLICY "exec_alerts_company_members_select"
  ON public.executive_alerts
  FOR SELECT
  USING (public.is_company_member(roofing_company_id));

CREATE POLICY "exec_alerts_company_members_insert"
  ON public.executive_alerts
  FOR INSERT
  WITH CHECK (public.is_company_member(roofing_company_id));

CREATE POLICY "exec_alerts_company_members_update_ack"
  ON public.executive_alerts
  FOR UPDATE
  USING (public.is_company_member(roofing_company_id))
  WITH CHECK (public.is_company_member(roofing_company_id));

-- Recommendations policies
CREATE POLICY "exec_recs_company_members_select"
  ON public.executive_recommendations
  FOR SELECT
  USING (public.is_company_member(roofing_company_id));

CREATE POLICY "exec_recs_company_members_insert"
  ON public.executive_recommendations
  FOR INSERT
  WITH CHECK (public.is_company_member(roofing_company_id));

CREATE POLICY "exec_recs_company_members_update_complete"
  ON public.executive_recommendations
  FOR UPDATE
  USING (public.is_company_member(roofing_company_id))
  WITH CHECK (public.is_company_member(roofing_company_id));

-- Service role full access for internal workers and AI engines
CREATE POLICY "exec_health_scores_service_role_all"
  ON public.executive_health_scores
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "exec_alerts_service_role_all"
  ON public.executive_alerts
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "exec_recs_service_role_all"
  ON public.executive_recommendations
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);


-- =====================================================================
-- PART 5 — COMMENTS & GRANTS
-- =====================================================================

COMMENT ON TABLE public.executive_health_scores IS 'Daily 0–100 business health scores per roofing company (Block 257900 — Executive Brain)';
COMMENT ON COLUMN public.executive_health_scores.categories IS 'JSON map of category -> score (sales, production, finances, reputation, staffing, etc)';

COMMENT ON TABLE public.executive_alerts IS 'Executive-level risk and opportunity alerts for roofing company owners (Block 257900 — Executive Brain)';
COMMENT ON COLUMN public.executive_alerts.context IS 'Structured JSON payload with underlying metrics/drilldowns powering the alert';

COMMENT ON TABLE public.executive_recommendations IS 'AI-generated owner-level action items and suggestions (Block 257900 — Executive Brain)';
COMMENT ON COLUMN public.executive_recommendations.context IS 'Structured JSON payload describing the data behind this recommendation';

GRANT SELECT, INSERT, UPDATE ON public.executive_health_scores TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.executive_alerts TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.executive_recommendations TO authenticated;

-- =====================================================================
-- END OF BLOCK 257900 MIGRATION
-- =====================================================================













