-- =========================================================
-- Block 22112 — SmartSend Roofing Action Queue v2
-- ("The Estimator Daily Command Center" — EXACTLY What To Do Today)
-- =========================================================
-- 
-- This is the next evolution after:
-- - Next-Action Engine
-- - Job Save Engine
-- - Message Builder
-- - Pipeline v2
-- - Health/Momentum/Experience/Risk
--
-- Now we build the page that makes SmartSend truly run the estimator's day.
--
-- Roofers need one page where they log in and instantly see:
-- "Here is EXACTLY what you must do today... in the exact order that makes your company the most money."
--
-- This is a revenue-prioritized task list that combines:
-- - job priority
-- - risk
-- - next best action
-- - overdue follow-ups
-- - proposal delays
-- - pipeline urgency
-- - job save events
-- - scheduling tasks
-- - message tasks
-- - reminders
-- - owner escalations
--
-- This is the daily workflow brain.
-- =========================================================

-- ============================================================================
-- 1. EXTEND action_queue_tasks TABLE WITH V2 COLUMNS
-- ============================================================================

-- Add action_priority column (1 = high, 2 = medium, 3 = low)
ALTER TABLE public.action_queue_tasks
  ADD COLUMN IF NOT EXISTS action_priority INTEGER DEFAULT 3 
  CHECK (action_priority >= 1 AND action_priority <= 3);

-- Add action_category column
ALTER TABLE public.action_queue_tasks
  ADD COLUMN IF NOT EXISTS action_category TEXT
  CHECK (action_category IN (
    'communication',
    'proposal',
    'inspection',
    'save',
    'ai',
    'stage',
    'time'
  ));

-- Add next_action column (link to next action engine)
ALTER TABLE public.action_queue_tasks
  ADD COLUMN IF NOT EXISTS next_action TEXT;

-- Add ai_message_draft column (pre-generated AI message for this task)
ALTER TABLE public.action_queue_tasks
  ADD COLUMN IF NOT EXISTS ai_message_draft TEXT;

-- Add due_at column (when this task is due)
ALTER TABLE public.action_queue_tasks
  ADD COLUMN IF NOT EXISTS due_at TIMESTAMPTZ;

-- Add auto_generated column (true if generated by system, false if manual)
ALTER TABLE public.action_queue_tasks
  ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN DEFAULT true;

-- Add next_action_reason column (explanation for why this action was recommended)
ALTER TABLE public.action_queue_tasks
  ADD COLUMN IF NOT EXISTS next_action_reason TEXT;

-- ============================================================================
-- 2. EXPAND task_type CHECK CONSTRAINT TO INCLUDE NEW ACTION TYPES
-- ============================================================================

-- Drop existing constraint
ALTER TABLE public.action_queue_tasks
  DROP CONSTRAINT IF EXISTS action_queue_tasks_task_type_check;

-- Recreate with expanded task types
ALTER TABLE public.action_queue_tasks
  ADD CONSTRAINT action_queue_tasks_task_type_check 
  CHECK (task_type IN (
    -- Communication Tasks
    'call_homeowner',
    'follow_up_hot',
    'follow_up_warm',
    'soft_reengagement',
    'tone_reset',
    'photo_request',
    'insurance_questions',
    'timeline_questions',
    'homeowner_reply_needed',
    
    -- Proposal Tasks
    'send_proposal',
    'resend_proposal',
    'explain_proposal',
    'update_proposal',
    'proposal_overdue',
    
    -- Inspection Tasks
    'schedule_inspection',
    'confirm_inspection',
    'upload_inspection_report',
    
    -- Save Tasks
    'save_critical_risk_job',
    'job_save',
    'urgent_recovery_message',
    'call_required',
    
    -- AI-Driven Tasks
    'next_best_action',
    'ai_message_draft',
    'coaching_prompt',
    
    -- Stage Management
    'move_job_to_next_stage',
    'complete_inspection',
    'confirm_finished_work',
    
    -- Time-Based Tasks
    'overdue_follow_up',
    'reminder_trigger',
    'no_reply_48h',
    
    -- Legacy/Other
    'reply_to_angry_homeowner',
    'book_estimate',
    'review_stuck_job',
    'owner_review_high_value',
    'resurrection_follow_up'
  ));

-- ============================================================================
-- 3. CREATE INDEXES FOR PERFORMANCE
-- ============================================================================

-- Index for priority-based queries
CREATE INDEX IF NOT EXISTS idx_action_queue_priority_category_status 
  ON public.action_queue_tasks (action_priority ASC, action_category, status) 
  WHERE status = 'open';

-- Index for due_at queries
CREATE INDEX IF NOT EXISTS idx_action_queue_due_at_priority 
  ON public.action_queue_tasks (due_at ASC, action_priority ASC) 
  WHERE status = 'open' AND due_at IS NOT NULL;

-- Index for auto_generated queries
CREATE INDEX IF NOT EXISTS idx_action_queue_auto_generated 
  ON public.action_queue_tasks (auto_generated, status) 
  WHERE status = 'open';

-- Index for next_action queries
CREATE INDEX IF NOT EXISTS idx_action_queue_next_action 
  ON public.action_queue_tasks (next_action, status) 
  WHERE status = 'open' AND next_action IS NOT NULL;

-- ============================================================================
-- 4. CREATE VIEW: action_queue_v2_view
-- ============================================================================
-- Enhanced view that joins action_queue_tasks with lead intelligence
-- for easy querying and display

CREATE OR REPLACE VIEW public.action_queue_v2_view AS
SELECT 
  aq.id,
  aq.workspace_id,
  aq.lead_id,
  aq.assigned_user_id,
  aq.task_type,
  aq.action_priority,
  aq.action_category,
  aq.next_action,
  aq.next_action_reason,
  aq.ai_message_draft,
  aq.due_at,
  aq.auto_generated,
  aq.priority as legacy_priority,
  aq.status,
  aq.source,
  aq.metadata,
  aq.created_at,
  aq.completed_at,
  
  -- Lead intelligence data
  l.first_name,
  l.last_name,
  l.email,
  l.status as lead_status,
  l.pipeline_stage,
  l.job_health_score,
  l.momentum_score,
  l.homeowner_experience_score,
  l.job_probability,
  l.risk_category,
  l.next_action as lead_next_action,
  l.next_action_reason as lead_next_action_reason,
  
  -- Job save status
  COALESCE(js.has_active_save, false) as is_in_save_mode,
  js.save_severity,
  
  -- Time calculations (in hours)
  CASE 
    WHEN l.last_reply_at IS NOT NULL 
    THEN EXTRACT(EPOCH FROM (NOW() - l.last_reply_at)) / 3600
    WHEN l.created_at IS NOT NULL
    THEN EXTRACT(EPOCH FROM (NOW() - l.created_at)) / 3600
    ELSE NULL
  END as hours_since_last_reply,
  CASE 
    WHEN l.last_message_at IS NOT NULL 
    THEN EXTRACT(EPOCH FROM (NOW() - l.last_message_at)) / 3600
    WHEN l.created_at IS NOT NULL
    THEN EXTRACT(EPOCH FROM (NOW() - l.created_at)) / 3600
    ELSE NULL
  END as hours_since_last_message,
  CASE 
    WHEN aq.due_at IS NOT NULL THEN EXTRACT(EPOCH FROM (aq.due_at - NOW())) / 3600
    ELSE NULL
  END as hours_until_due,
  CASE 
    WHEN aq.due_at IS NOT NULL AND aq.due_at < NOW() THEN true
    ELSE false
  END as is_overdue,
  
  -- Proposal status
  COALESCE((SELECT COUNT(*) > 0 FROM public.proposals WHERE lead_id = l.id), false) as has_proposal,
  (SELECT MAX(created_at) FROM public.proposals WHERE lead_id = l.id) as last_proposal_at,
  CASE 
    WHEN (SELECT MAX(created_at) FROM public.proposals WHERE lead_id = l.id) IS NOT NULL 
    THEN EXTRACT(EPOCH FROM (NOW() - (SELECT MAX(created_at) FROM public.proposals WHERE lead_id = l.id))) / 3600
    ELSE NULL
  END as proposal_delay_hours,
  
  -- Tone
  l.homeowner_tone as last_tone

FROM public.action_queue_tasks aq
LEFT JOIN public.leads l ON l.id = aq.lead_id
LEFT JOIN (
  SELECT 
    lead_id,
    COUNT(*) > 0 as has_active_save,
    MAX(severity) as save_severity
  FROM public.job_save_events
  WHERE status = 'active'
  GROUP BY lead_id
) js ON js.lead_id = l.id;

-- Grant access
GRANT SELECT ON public.action_queue_v2_view TO authenticated;
GRANT SELECT ON public.action_queue_v2_view TO service_role;

COMMENT ON VIEW public.action_queue_v2_view IS 'Block 22112: Enhanced action queue view with lead intelligence for Action Queue v2 Daily Command Center';

-- ============================================================================
-- 5. COMMENTS FOR DOCUMENTATION
-- ============================================================================

COMMENT ON COLUMN public.action_queue_tasks.action_priority IS 'Block 22112: Priority level (1 = high/revenue urgent, 2 = medium/move forward, 3 = low/cleanup)';
COMMENT ON COLUMN public.action_queue_tasks.action_category IS 'Block 22112: Category: communication, proposal, inspection, save, ai, stage, time';
COMMENT ON COLUMN public.action_queue_tasks.next_action IS 'Block 22112: Link to next action engine recommendation';
COMMENT ON COLUMN public.action_queue_tasks.ai_message_draft IS 'Block 22112: Pre-generated AI message draft for this task';
COMMENT ON COLUMN public.action_queue_tasks.due_at IS 'Block 22112: When this task is due';
COMMENT ON COLUMN public.action_queue_tasks.auto_generated IS 'Block 22112: True if generated by system, false if manual';
COMMENT ON COLUMN public.action_queue_tasks.next_action_reason IS 'Block 22112: Explanation for why this action was recommended';

