-- Block 76000 — SmartSend Roofing
-- "Elite Email Deliverability Engine + Cold Outreach Warm-Up" v1
-- Complete deliverability system with domain verification, warm-up, and reputation management

-- ============================================================================
-- PART 1 — SENDING DOMAINS TABLE
-- ============================================================================
-- Domains connected by roofing company/org for email sending

CREATE TABLE IF NOT EXISTS public.sending_domains (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  roofing_company_id uuid REFERENCES public.roofing_companies(id) ON DELETE CASCADE,
  
  -- Domain Information
  domain text NOT NULL,                    -- e.g., "smithroofing.com"
  
  -- DNS Records (generated by SmartSend)
  dkim_record text,                        -- DKIM public key record
  dkim_selector text DEFAULT 'default',    -- DKIM selector
  spf_record text,                         -- SPF record value
  dmarc_record text,                       -- DMARC policy record
  
  -- DNS Verification Status
  dns_status text DEFAULT 'not_connected' CHECK (dns_status IN ('not_connected', 'partially_connected', 'fully_authenticated')),
  spf_verified boolean DEFAULT false,
  dkim_verified boolean DEFAULT false,
  dmarc_verified boolean DEFAULT false,
  last_dns_check_at timestamptz,
  
  -- Warm-Up Status
  warmup_status text DEFAULT 'not_started' CHECK (warmup_status IN ('not_started', 'warming', 'ready', 'paused', 'failed')),
  warmup_started_at timestamptz,
  warmup_completed_at timestamptz,
  
  -- Sending Reputation
  sending_reputation text DEFAULT 'poor' CHECK (sending_reputation IN ('poor', 'fair', 'good', 'excellent')),
  reputation_score numeric DEFAULT 0 CHECK (reputation_score >= 0 AND reputation_score <= 100),
  
  -- Reputation Metrics (calculated from warmup_logs)
  total_sent integer DEFAULT 0,
  total_delivered integer DEFAULT 0,
  total_opened integer DEFAULT 0,
  total_replied integer DEFAULT 0,
  total_bounced integer DEFAULT 0,
  total_complained integer DEFAULT 0,
  deliverability_rate numeric DEFAULT 0,   -- delivered / sent
  open_rate numeric DEFAULT 0,             -- opened / delivered
  reply_rate numeric DEFAULT 0,             -- replied / delivered
  bounce_rate numeric DEFAULT 0,            -- bounced / sent
  complaint_rate numeric DEFAULT 0,         -- complained / sent
  
  -- Throttle Status
  is_throttled boolean DEFAULT false,
  throttle_reason text,
  throttle_until timestamptz,
  
  -- Metadata
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  
  -- Ensure unique domain per org
  CONSTRAINT unique_domain_per_org UNIQUE (org_id, domain)
);

CREATE INDEX IF NOT EXISTS idx_sending_domains_org ON public.sending_domains(org_id);
CREATE INDEX IF NOT EXISTS idx_sending_domains_company ON public.sending_domains(roofing_company_id) WHERE roofing_company_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sending_domains_domain ON public.sending_domains(domain);
CREATE INDEX IF NOT EXISTS idx_sending_domains_warmup_status ON public.sending_domains(warmup_status);
CREATE INDEX IF NOT EXISTS idx_sending_domains_reputation ON public.sending_domains(sending_reputation, reputation_score);
CREATE INDEX IF NOT EXISTS idx_sending_domains_throttled ON public.sending_domains(is_throttled, throttle_until) WHERE is_throttled = true;

COMMENT ON TABLE public.sending_domains IS 'Sending domains for email deliverability with DNS verification and warm-up tracking (Block 76000)';

-- ============================================================================
-- PART 2 — WARM-UP SCHEDULE TABLE
-- ============================================================================
-- Daily schedule for domain warm-up emails

CREATE TABLE IF NOT EXISTS public.warmup_schedule (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  domain_id uuid NOT NULL REFERENCES public.sending_domains(id) ON DELETE CASCADE,
  
  -- Schedule Details
  day integer NOT NULL CHECK (day > 0),    -- Day number (1, 2, 3, ...)
  emails_to_send integer NOT NULL CHECK (emails_to_send > 0),
  
  -- Status
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'skipped', 'failed')),
  sent_at timestamptz,
  
  -- Metadata
  created_at timestamptz NOT NULL DEFAULT now(),
  
  -- Ensure unique day per domain
  CONSTRAINT unique_day_per_domain UNIQUE (domain_id, day)
);

CREATE INDEX IF NOT EXISTS idx_warmup_schedule_domain ON public.warmup_schedule(domain_id, day);
CREATE INDEX IF NOT EXISTS idx_warmup_schedule_status ON public.warmup_schedule(status) WHERE status = 'pending';

COMMENT ON TABLE public.warmup_schedule IS 'Daily warm-up email schedule for sending domains (Block 76000)';

-- ============================================================================
-- PART 3 — WARM-UP LOGS TABLE
-- ============================================================================
-- Detailed logs of warm-up email sends and results

CREATE TABLE IF NOT EXISTS public.warmup_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  domain_id uuid NOT NULL REFERENCES public.sending_domains(id) ON DELETE CASCADE,
  schedule_id uuid REFERENCES public.warmup_schedule(id) ON DELETE SET NULL,
  
  -- Send Metrics
  sent integer DEFAULT 0,
  delivered integer DEFAULT 0,
  opened integer DEFAULT 0,
  replied integer DEFAULT 0,
  bounced integer DEFAULT 0,
  complained integer DEFAULT 0,
  marked_spam integer DEFAULT 0,
  
  -- Calculated Rates
  deliverability_rate numeric,
  open_rate numeric,
  reply_rate numeric,
  bounce_rate numeric,
  complaint_rate numeric,
  
  -- Provider Feedback
  gmail_feedback jsonb DEFAULT '{}'::jsonb,    -- Gmail-specific feedback
  outlook_feedback jsonb DEFAULT '{}'::jsonb,  -- Outlook-specific feedback
  spam_score numeric,                          -- Overall spam score (0-100)
  
  -- Timestamp
  log_date date NOT NULL DEFAULT CURRENT_DATE,
  timestamp timestamptz NOT NULL DEFAULT now(),
  
  -- Ensure one log per domain per day
  CONSTRAINT unique_log_per_domain_per_day UNIQUE (domain_id, log_date)
);

CREATE INDEX IF NOT EXISTS idx_warmup_logs_domain ON public.warmup_logs(domain_id, log_date DESC);
CREATE INDEX IF NOT EXISTS idx_warmup_logs_timestamp ON public.warmup_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_warmup_logs_schedule ON public.warmup_logs(schedule_id) WHERE schedule_id IS NOT NULL;

COMMENT ON TABLE public.warmup_logs IS 'Daily warm-up email logs with deliverability metrics (Block 76000)';

-- ============================================================================
-- PART 4 — SEND QUEUE TABLE
-- ============================================================================
-- Queue for actual campaign emails with domain rotation and reputation checks

CREATE TABLE IF NOT EXISTS public.send_queue (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
  domain_id uuid REFERENCES public.sending_domains(id) ON DELETE SET NULL,
  campaign_id uuid,                         -- References campaigns table (if exists)
  
  -- Email Details
  recipient text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  body_html text,
  
  -- Sending Configuration
  from_email text,                          -- Override from address
  from_name text,                           -- Override from name
  reply_to text,
  
  -- Status & Retry Logic
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'queued', 'sending', 'sent', 'failed', 'throttled', 'skipped')),
  retries integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  error_message text,
  
  -- Scheduling
  scheduled_at timestamptz DEFAULT now(),
  sent_at timestamptz,
  
  -- Spam Score (pre-send check)
  spam_score numeric,
  spam_score_details jsonb DEFAULT '{}'::jsonb,
  
  -- Metadata
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_send_queue_org ON public.send_queue(org_id);
CREATE INDEX IF NOT EXISTS idx_send_queue_domain ON public.send_queue(domain_id) WHERE domain_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_send_queue_status ON public.send_queue(status, scheduled_at) WHERE status IN ('pending', 'queued');
CREATE INDEX IF NOT EXISTS idx_send_queue_campaign ON public.send_queue(campaign_id) WHERE campaign_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_send_queue_scheduled ON public.send_queue(scheduled_at) WHERE status IN ('pending', 'queued');

COMMENT ON TABLE public.send_queue IS 'Email send queue with domain rotation and reputation-based throttling (Block 76000)';

-- ============================================================================
-- PART 5 — TRIGGERS & FUNCTIONS
-- ============================================================================

-- Update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_sending_domains_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_sending_domains_updated_at
BEFORE UPDATE ON public.sending_domains
FOR EACH ROW
EXECUTE FUNCTION public.update_sending_domains_updated_at();

CREATE OR REPLACE FUNCTION public.update_send_queue_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_send_queue_updated_at
BEFORE UPDATE ON public.send_queue
FOR EACH ROW
EXECUTE FUNCTION public.update_send_queue_updated_at();

-- Function to calculate and update domain reputation
CREATE OR REPLACE FUNCTION public.update_domain_reputation(p_domain_id uuid)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  v_total_sent integer;
  v_total_delivered integer;
  v_total_opened integer;
  v_total_replied integer;
  v_total_bounced integer;
  v_total_complained integer;
  v_deliverability_rate numeric;
  v_open_rate numeric;
  v_reply_rate numeric;
  v_bounce_rate numeric;
  v_complaint_rate numeric;
  v_reputation_score numeric;
  v_sending_reputation text;
BEGIN
  -- Aggregate metrics from warmup_logs
  SELECT 
    COALESCE(SUM(sent), 0),
    COALESCE(SUM(delivered), 0),
    COALESCE(SUM(opened), 0),
    COALESCE(SUM(replied), 0),
    COALESCE(SUM(bounced), 0),
    COALESCE(SUM(complained), 0)
  INTO 
    v_total_sent,
    v_total_delivered,
    v_total_opened,
    v_total_replied,
    v_total_bounced,
    v_total_complained
  FROM public.warmup_logs
  WHERE domain_id = p_domain_id;
  
  -- Calculate rates
  v_deliverability_rate := CASE WHEN v_total_sent > 0 THEN (v_total_delivered::numeric / v_total_sent::numeric * 100) ELSE 0 END;
  v_open_rate := CASE WHEN v_total_delivered > 0 THEN (v_total_opened::numeric / v_total_delivered::numeric * 100) ELSE 0 END;
  v_reply_rate := CASE WHEN v_total_delivered > 0 THEN (v_total_replied::numeric / v_total_delivered::numeric * 100) ELSE 0 END;
  v_bounce_rate := CASE WHEN v_total_sent > 0 THEN (v_total_bounced::numeric / v_total_sent::numeric * 100) ELSE 0 END;
  v_complaint_rate := CASE WHEN v_total_sent > 0 THEN (v_total_complained::numeric / v_total_sent::numeric * 100) ELSE 0 END;
  
  -- Calculate reputation score (0-100)
  -- Formula: deliverability (40%) + open rate (30%) + reply rate (20%) - bounce rate (5%) - complaint rate (5%)
  v_reputation_score := 
    (v_deliverability_rate * 0.4) +
    (v_open_rate * 0.3) +
    (v_reply_rate * 0.2) -
    (v_bounce_rate * 0.05) -
    (v_complaint_rate * 0.05);
  
  -- Clamp to 0-100
  v_reputation_score := GREATEST(0, LEAST(100, v_reputation_score));
  
  -- Determine reputation tier
  IF v_reputation_score >= 80 AND v_bounce_rate < 2 AND v_complaint_rate < 0.1 THEN
    v_sending_reputation := 'excellent';
  ELSIF v_reputation_score >= 60 AND v_bounce_rate < 5 AND v_complaint_rate < 0.5 THEN
    v_sending_reputation := 'good';
  ELSIF v_reputation_score >= 40 AND v_bounce_rate < 10 THEN
    v_sending_reputation := 'fair';
  ELSE
    v_sending_reputation := 'poor';
  END IF;
  
  -- Update sending_domains
  UPDATE public.sending_domains
  SET
    total_sent = v_total_sent,
    total_delivered = v_total_delivered,
    total_opened = v_total_opened,
    total_replied = v_total_replied,
    total_bounced = v_total_bounced,
    total_complained = v_total_complained,
    deliverability_rate = v_deliverability_rate,
    open_rate = v_open_rate,
    reply_rate = v_reply_rate,
    bounce_rate = v_bounce_rate,
    complaint_rate = v_complaint_rate,
    reputation_score = v_reputation_score,
    sending_reputation = v_sending_reputation
  WHERE id = p_domain_id;
END;
$$;

COMMENT ON FUNCTION public.update_domain_reputation IS 'Calculates and updates domain reputation based on warm-up logs (Block 76000)';

-- Function to initialize warm-up schedule
CREATE OR REPLACE FUNCTION public.initialize_warmup_schedule(p_domain_id uuid)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  v_day integer;
  v_emails integer;
BEGIN
  -- Standard warm-up schedule: gradual increase over 30 days
  -- Day 1: 3, Day 2: 5, Day 3: 8, Day 4: 12, Day 5: 20, Day 10: 35, Day 20: 60, Day 30: 100
  FOR v_day IN 1..30 LOOP
    CASE v_day
      WHEN 1 THEN v_emails := 3;
      WHEN 2 THEN v_emails := 5;
      WHEN 3 THEN v_emails := 8;
      WHEN 4 THEN v_emails := 12;
      WHEN 5 THEN v_emails := 20;
      WHEN 6 THEN v_emails := 25;
      WHEN 7 THEN v_emails := 30;
      WHEN 8 THEN v_emails := 32;
      WHEN 9 THEN v_emails := 34;
      WHEN 10 THEN v_emails := 35;
      WHEN 11 THEN v_emails := 38;
      WHEN 12 THEN v_emails := 40;
      WHEN 13 THEN v_emails := 42;
      WHEN 14 THEN v_emails := 45;
      WHEN 15 THEN v_emails := 48;
      WHEN 16 THEN v_emails := 50;
      WHEN 17 THEN v_emails := 52;
      WHEN 18 THEN v_emails := 55;
      WHEN 19 THEN v_emails := 58;
      WHEN 20 THEN v_emails := 60;
      WHEN 21 THEN v_emails := 65;
      WHEN 22 THEN v_emails := 70;
      WHEN 23 THEN v_emails := 75;
      WHEN 24 THEN v_emails := 80;
      WHEN 25 THEN v_emails := 85;
      WHEN 26 THEN v_emails := 90;
      WHEN 27 THEN v_emails := 95;
      WHEN 28 THEN v_emails := 98;
      WHEN 29 THEN v_emails := 99;
      WHEN 30 THEN v_emails := 100;
      ELSE v_emails := 100;
    END CASE;
    
    INSERT INTO public.warmup_schedule (domain_id, day, emails_to_send)
    VALUES (p_domain_id, v_day, v_emails)
    ON CONFLICT (domain_id, day) DO NOTHING;
  END LOOP;
  
  -- Update domain warmup status
  UPDATE public.sending_domains
  SET warmup_status = 'warming', warmup_started_at = now()
  WHERE id = p_domain_id;
END;
$$;

COMMENT ON FUNCTION public.initialize_warmup_schedule IS 'Initializes 30-day warm-up schedule for a domain (Block 76000)';

-- ============================================================================
-- PART 6 — ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Enable RLS
ALTER TABLE public.sending_domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warmup_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warmup_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.send_queue ENABLE ROW LEVEL SECURITY;

-- Helper function to check org membership
CREATE OR REPLACE FUNCTION public.is_org_member_deliverability(_org_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS(
    SELECT 1 FROM public.org_members
    WHERE org_id = _org_id AND user_id = auth.uid()
  ) OR EXISTS(
    SELECT 1 FROM public.organization_members
    WHERE org_id = _org_id AND user_id = auth.uid()
  );
$$;

-- RLS Policies for sending_domains
CREATE POLICY "sending_domains_select" ON public.sending_domains
  FOR SELECT USING (is_org_member_deliverability(org_id));

CREATE POLICY "sending_domains_insert" ON public.sending_domains
  FOR INSERT WITH CHECK (is_org_member_deliverability(org_id));

CREATE POLICY "sending_domains_update" ON public.sending_domains
  FOR UPDATE USING (is_org_member_deliverability(org_id));

CREATE POLICY "sending_domains_delete" ON public.sending_domains
  FOR DELETE USING (is_org_member_deliverability(org_id));

-- RLS Policies for warmup_schedule
CREATE POLICY "warmup_schedule_select" ON public.warmup_schedule
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.sending_domains sd
      WHERE sd.id = warmup_schedule.domain_id
      AND is_org_member_deliverability(sd.org_id)
    )
  );

CREATE POLICY "warmup_schedule_insert" ON public.warmup_schedule
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.sending_domains sd
      WHERE sd.id = warmup_schedule.domain_id
      AND is_org_member_deliverability(sd.org_id)
    )
  );

CREATE POLICY "warmup_schedule_update" ON public.warmup_schedule
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.sending_domains sd
      WHERE sd.id = warmup_schedule.domain_id
      AND is_org_member_deliverability(sd.org_id)
    )
  );

-- RLS Policies for warmup_logs
CREATE POLICY "warmup_logs_select" ON public.warmup_logs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.sending_domains sd
      WHERE sd.id = warmup_logs.domain_id
      AND is_org_member_deliverability(sd.org_id)
    )
  );

CREATE POLICY "warmup_logs_insert" ON public.warmup_logs
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.sending_domains sd
      WHERE sd.id = warmup_logs.domain_id
      AND is_org_member_deliverability(sd.org_id)
    )
  );

-- RLS Policies for send_queue
CREATE POLICY "send_queue_select" ON public.send_queue
  FOR SELECT USING (is_org_member_deliverability(org_id));

CREATE POLICY "send_queue_insert" ON public.send_queue
  FOR INSERT WITH CHECK (is_org_member_deliverability(org_id));

CREATE POLICY "send_queue_update" ON public.send_queue
  FOR UPDATE USING (is_org_member_deliverability(org_id));

-- Service role bypass (for cron jobs and background workers)
CREATE POLICY "sending_domains_service_role_all" ON public.sending_domains
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "warmup_schedule_service_role_all" ON public.warmup_schedule
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "warmup_logs_service_role_all" ON public.warmup_logs
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "send_queue_service_role_all" ON public.send_queue
  FOR ALL TO service_role USING (true) WITH CHECK (true);



























