-- =========================================================
-- Block 254600 — SmartSend AI Compliance & Legal Shield v1
-- "OSHA Logs, Incident Documentation, Safety Compliance Automation, Legal Protection, Required Recordkeeping"
-- =========================================================
-- 
-- This block protects roofing companies from the #1 thing that can destroy them overnight:
-- legal risk + safety violations + missing documentation.
-- 
-- Roofers get sued because:
-- - no proof of safety meetings
-- - no record of PPE usage
-- - no OSHA 300/301 logs
-- - no incident documentation
-- - no photos of hazards
-- - no training logs
-- - no compliance documents for subs
-- - no employee signatures
-- - no jobsite checklists
-- - no timeline of what happened
-- 
-- SmartSend becomes the legal shield that roofing companies desperately need.
-- =========================================================

-- ============================================================================
-- PART 1 — OSHA INCIDENTS TABLE
-- ============================================================================
-- Tracks workplace injuries and incidents for OSHA compliance

CREATE TABLE IF NOT EXISTS public.osha_incidents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,
  job_id uuid REFERENCES public.jobs(id) ON DELETE SET NULL,
  employee_id uuid REFERENCES public.workforce_employees(id) ON DELETE SET NULL,
  
  -- Incident Details
  description text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('minor', 'moderate', 'serious', 'fatal')),
  injury_type text, -- cut, fall, strain, burn, etc.
  body_part text, -- hand, leg, back, head, etc.
  
  -- Documentation
  photos text[], -- Array of photo URLs
  video_url text,
  location text, -- Where on jobsite
  date timestamptz NOT NULL,
  
  -- AI-Generated Compliance Fields
  osha_classification text, -- Generated by AI
  root_cause_summary text, -- Generated by AI
  corrective_action_plan text, -- Generated by AI
  osha_301_completed boolean DEFAULT false,
  
  -- Metadata
  reported_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_osha_incidents_company ON public.osha_incidents(company_id);
CREATE INDEX IF NOT EXISTS idx_osha_incidents_job ON public.osha_incidents(job_id) WHERE job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_osha_incidents_employee ON public.osha_incidents(employee_id) WHERE employee_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_osha_incidents_date ON public.osha_incidents(company_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_osha_incidents_severity ON public.osha_incidents(company_id, severity);

COMMENT ON TABLE public.osha_incidents IS 'Tracks workplace injuries and incidents for OSHA compliance (Block 254600)';
COMMENT ON COLUMN public.osha_incidents.severity IS 'Severity: minor, moderate, serious, fatal';
COMMENT ON COLUMN public.osha_incidents.osha_301_completed IS 'Whether OSHA 301 form has been completed for this incident';

-- ============================================================================
-- PART 2 — OSHA LOGS TABLE
-- ============================================================================
-- Stores OSHA 300, 301, and 300A forms

CREATE TABLE IF NOT EXISTS public.osha_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,
  
  -- Form Type
  form_type text NOT NULL CHECK (form_type IN ('OSHA_300', 'OSHA_301', 'OSHA_300A')),
  year int NOT NULL,
  
  -- Form Data (JSONB for flexibility)
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  
  -- Generated PDF
  pdf_url text,
  
  -- Metadata
  generated_at timestamptz DEFAULT now(),
  generated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_osha_logs_company ON public.osha_logs(company_id);
CREATE INDEX IF NOT EXISTS idx_osha_logs_form_type ON public.osha_logs(company_id, form_type, year);
CREATE INDEX IF NOT EXISTS idx_osha_logs_year ON public.osha_logs(company_id, year DESC);

COMMENT ON TABLE public.osha_logs IS 'Stores OSHA 300, 301, and 300A forms (Block 254600)';
COMMENT ON COLUMN public.osha_logs.form_type IS 'Form type: OSHA_300, OSHA_301, OSHA_300A';
COMMENT ON COLUMN public.osha_logs.data IS 'JSONB containing all form data';

-- ============================================================================
-- PART 3 — SAFETY MEETINGS TABLE
-- ============================================================================
-- Tracks daily safety meetings with digital signatures

CREATE TABLE IF NOT EXISTS public.safety_meetings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,
  job_id uuid REFERENCES public.jobs(id) ON DELETE SET NULL,
  
  -- Meeting Details
  topic text NOT NULL,
  notes text,
  date date NOT NULL,
  
  -- Attendees
  attendees uuid[] NOT NULL DEFAULT '{}', -- Array of workforce_employees.id
  attendee_signatures jsonb DEFAULT '{}'::jsonb, -- {employee_id: {signed_at, signature_data}}
  
  -- Status
  signed boolean DEFAULT false,
  signed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, -- Foreman/PM who signed
  signed_at timestamptz,
  
  -- Metadata
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_safety_meetings_company ON public.safety_meetings(company_id);
CREATE INDEX IF NOT EXISTS idx_safety_meetings_job ON public.safety_meetings(job_id) WHERE job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_safety_meetings_date ON public.safety_meetings(company_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_safety_meetings_signed ON public.safety_meetings(company_id, signed, date DESC);

COMMENT ON TABLE public.safety_meetings IS 'Tracks daily safety meetings with digital signatures (Block 254600)';
COMMENT ON COLUMN public.safety_meetings.attendees IS 'Array of workforce_employees.id who attended';
COMMENT ON COLUMN public.safety_meetings.attendee_signatures IS 'JSONB: {employee_id: {signed_at, signature_data}}';

-- ============================================================================
-- PART 4 — PPE CHECKS TABLE
-- ============================================================================
-- Tracks Personal Protective Equipment verification (AI-verified from photos)

CREATE TABLE IF NOT EXISTS public.ppe_checks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,
  job_id uuid REFERENCES public.jobs(id) ON DELETE SET NULL,
  employee_id uuid REFERENCES public.workforce_employees(id) ON DELETE SET NULL,
  
  -- PPE Items
  hard_hat boolean DEFAULT false,
  harness boolean DEFAULT false,
  boots boolean DEFAULT false,
  eye_protection boolean DEFAULT false,
  vest boolean DEFAULT false,
  gloves boolean DEFAULT false,
  
  -- AI Verification
  ai_verified boolean DEFAULT false,
  photo_url text, -- Photo used for AI verification
  ai_confidence numeric, -- AI confidence score (0-100)
  ai_notes text, -- AI-detected issues
  
  -- Manual Override
  manually_verified boolean DEFAULT false,
  verified_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  
  -- Status
  compliant boolean DEFAULT false,
  violation_notes text,
  
  -- Metadata
  check_date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ppe_checks_company ON public.ppe_checks(company_id);
CREATE INDEX IF NOT EXISTS idx_ppe_checks_job ON public.ppe_checks(job_id) WHERE job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppe_checks_employee ON public.ppe_checks(employee_id) WHERE employee_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ppe_checks_date ON public.ppe_checks(company_id, check_date DESC);
CREATE INDEX IF NOT EXISTS idx_ppe_checks_compliant ON public.ppe_checks(company_id, compliant, check_date DESC);

COMMENT ON TABLE public.ppe_checks IS 'Tracks PPE verification (AI-verified from photos) (Block 254600)';
COMMENT ON COLUMN public.ppe_checks.ai_verified IS 'Whether AI verified PPE from photo';
COMMENT ON COLUMN public.ppe_checks.compliant IS 'Whether employee is compliant with all required PPE';

-- ============================================================================
-- PART 5 — HAZARD REPORTS TABLE
-- ============================================================================
-- Allows employees to report jobsite hazards instantly

CREATE TABLE IF NOT EXISTS public.hazard_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,
  job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  reporter_id uuid REFERENCES public.workforce_employees(id) ON DELETE SET NULL,
  
  -- Hazard Details
  description text NOT NULL,
  hazard_type text, -- loose_decking, soft_spots, electrical, wasp_nest, broken_ladder, unsafe_behavior, other
  location text, -- Where on jobsite
  severity text CHECK (severity IN ('low', 'medium', 'high', 'critical')) DEFAULT 'medium',
  
  -- Documentation
  photo_url text,
  
  -- Resolution
  resolved boolean DEFAULT false,
  resolved_at timestamptz,
  resolved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  resolution_notes text,
  
  -- Metadata
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_hazard_reports_company ON public.hazard_reports(company_id);
CREATE INDEX IF NOT EXISTS idx_hazard_reports_job ON public.hazard_reports(job_id);
CREATE INDEX IF NOT EXISTS idx_hazard_reports_reporter ON public.hazard_reports(reporter_id) WHERE reporter_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_hazard_reports_resolved ON public.hazard_reports(company_id, resolved, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_hazard_reports_severity ON public.hazard_reports(company_id, severity, resolved);

COMMENT ON TABLE public.hazard_reports IS 'Allows employees to report jobsite hazards instantly (Block 254600)';
COMMENT ON COLUMN public.hazard_reports.hazard_type IS 'Type: loose_decking, soft_spots, electrical, wasp_nest, broken_ladder, unsafe_behavior, other';
COMMENT ON COLUMN public.hazard_reports.severity IS 'Severity: low, medium, high, critical';

-- ============================================================================
-- PART 6 — TRAINING RECORDS TABLE
-- ============================================================================
-- Tracks employee training and certifications

CREATE TABLE IF NOT EXISTS public.training_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,
  employee_id uuid NOT NULL REFERENCES public.workforce_employees(id) ON DELETE CASCADE,
  
  -- Training Details
  training_type text NOT NULL, -- fall_protection, ladder_safety, ppe, first_aid, osha_10, osha_30, etc.
  training_name text, -- Specific course name
  completed_on date NOT NULL,
  expires_on date, -- null = no expiration
  
  -- Certification
  certificate_url text,
  cert_number text,
  issuing_organization text,
  
  -- Status
  is_required boolean DEFAULT false, -- Required for their role
  is_expired boolean GENERATED ALWAYS AS (
    CASE 
      WHEN expires_on IS NULL THEN false
      WHEN expires_on < CURRENT_DATE THEN true
      ELSE false
    END
  ) STORED,
  
  -- Metadata
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_training_records_company ON public.training_records(company_id);
CREATE INDEX IF NOT EXISTS idx_training_records_employee ON public.training_records(employee_id);
CREATE INDEX IF NOT EXISTS idx_training_records_type ON public.training_records(company_id, training_type);
CREATE INDEX IF NOT EXISTS idx_training_records_expires ON public.training_records(company_id, expires_on) WHERE expires_on IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_training_records_expired ON public.training_records(company_id, is_expired) WHERE is_expired = true;

COMMENT ON TABLE public.training_records IS 'Tracks employee training and certifications (Block 254600)';
COMMENT ON COLUMN public.training_records.training_type IS 'Type: fall_protection, ladder_safety, ppe, first_aid, osha_10, osha_30, etc.';
COMMENT ON COLUMN public.training_records.is_expired IS 'Computed column: true if expires_on < CURRENT_DATE';

-- ============================================================================
-- PART 7 — SUBCONTRACTOR COMPLIANCE TABLE
-- ============================================================================
-- Tracks subcontractor compliance documents (W9, COI, Workers Comp, etc.)

CREATE TABLE IF NOT EXISTS public.subcontractor_compliance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,
  subcontractor_id uuid, -- References subcontractors table if exists, or store name
  
  -- Subcontractor Info
  subcontractor_name text NOT NULL,
  contact_name text,
  contact_email text,
  contact_phone text,
  
  -- Compliance Documents
  w9_on_file boolean DEFAULT false,
  w9_url text,
  w9_expires_on date,
  
  coi_on_file boolean DEFAULT false, -- Certificate of Insurance
  coi_url text,
  coi_expires_on date,
  coi_coverage_amount numeric,
  
  workers_comp_on_file boolean DEFAULT false,
  workers_comp_url text,
  workers_comp_expires_on date,
  
  safety_certifications jsonb DEFAULT '[]'::jsonb, -- Array of certs
  
  -- Status
  is_compliant boolean GENERATED ALWAYS AS (
    CASE
      WHEN w9_on_file = false THEN false
      WHEN coi_on_file = false THEN false
      WHEN workers_comp_on_file = false THEN false
      WHEN coi_expires_on IS NOT NULL AND coi_expires_on < CURRENT_DATE THEN false
      WHEN workers_comp_expires_on IS NOT NULL AND workers_comp_expires_on < CURRENT_DATE THEN false
      ELSE true
    END
  ) STORED,
  
  -- Metadata
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subcontractor_compliance_company ON public.subcontractor_compliance(company_id);
CREATE INDEX IF NOT EXISTS idx_subcontractor_compliance_compliant ON public.subcontractor_compliance(company_id, is_compliant);
CREATE INDEX IF NOT EXISTS idx_subcontractor_compliance_expires ON public.subcontractor_compliance(company_id, coi_expires_on, workers_comp_expires_on);

COMMENT ON TABLE public.subcontractor_compliance IS 'Tracks subcontractor compliance documents (Block 254600)';
COMMENT ON COLUMN public.subcontractor_compliance.is_compliant IS 'Computed: true if all required docs on file and not expired';

-- ============================================================================
-- PART 8 — DAILY SAFETY LOGS TABLE
-- ============================================================================
-- Daily safety checklists that crews must complete

CREATE TABLE IF NOT EXISTS public.daily_safety_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,
  job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  
  -- Log Date
  log_date date NOT NULL,
  
  -- Safety Checklist
  safety_checklist_completed boolean DEFAULT false,
  ppe_verification_completed boolean DEFAULT false,
  hazard_scan_completed boolean DEFAULT false,
  attendance_list_completed boolean DEFAULT false,
  safety_meeting_completed boolean DEFAULT false,
  
  -- Checklist Details (JSONB for flexibility)
  checklist_data jsonb DEFAULT '{}'::jsonb,
  
  -- Signatures
  foreman_signed boolean DEFAULT false,
  foreman_signature_data jsonb,
  foreman_signed_at timestamptz,
  foreman_id uuid REFERENCES public.workforce_employees(id) ON DELETE SET NULL,
  
  -- Status
  is_complete boolean GENERATED ALWAYS AS (
    safety_checklist_completed AND
    ppe_verification_completed AND
    hazard_scan_completed AND
    attendance_list_completed AND
    safety_meeting_completed AND
    foreman_signed
  ) STORED,
  
  -- Metadata
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  
  -- Unique constraint: one log per job per day
  UNIQUE(job_id, log_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_safety_logs_company ON public.daily_safety_logs(company_id);
CREATE INDEX IF NOT EXISTS idx_daily_safety_logs_job ON public.daily_safety_logs(job_id);
CREATE INDEX IF NOT EXISTS idx_daily_safety_logs_date ON public.daily_safety_logs(company_id, log_date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_safety_logs_complete ON public.daily_safety_logs(company_id, is_complete, log_date DESC);

COMMENT ON TABLE public.daily_safety_logs IS 'Daily safety checklists that crews must complete (Block 254600)';
COMMENT ON COLUMN public.daily_safety_logs.is_complete IS 'Computed: true if all checklist items completed and foreman signed';

-- ============================================================================
-- PART 9 — LEGAL RISK ALERTS TABLE
-- ============================================================================
-- System-generated alerts for legal risk patterns

CREATE TABLE IF NOT EXISTS public.legal_risk_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.roofing_companies(id) ON DELETE CASCADE,
  
  -- Alert Details
  alert_type text NOT NULL, -- ppe_violations, repeated_incidents, unsafe_speed, incomplete_meetings, untrained_employees, missing_signatures, unresolved_hazards
  severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  title text NOT NULL,
  message text NOT NULL,
  
  -- Related Entities
  related_job_id uuid REFERENCES public.jobs(id) ON DELETE SET NULL,
  related_employee_id uuid REFERENCES public.workforce_employees(id) ON DELETE SET NULL,
  related_crew_id uuid, -- If crew tracking exists
  
  -- Status
  acknowledged boolean DEFAULT false,
  acknowledged_at timestamptz,
  acknowledged_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  resolved boolean DEFAULT false,
  resolved_at timestamptz,
  resolved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  
  -- Metadata
  metadata jsonb DEFAULT '{}'::jsonb, -- Additional context
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_legal_risk_alerts_company ON public.legal_risk_alerts(company_id);
CREATE INDEX IF NOT EXISTS idx_legal_risk_alerts_type ON public.legal_risk_alerts(company_id, alert_type);
CREATE INDEX IF NOT EXISTS idx_legal_risk_alerts_severity ON public.legal_risk_alerts(company_id, severity, resolved);
CREATE INDEX IF NOT EXISTS idx_legal_risk_alerts_resolved ON public.legal_risk_alerts(company_id, resolved, created_at DESC);

COMMENT ON TABLE public.legal_risk_alerts IS 'System-generated alerts for legal risk patterns (Block 254600)';
COMMENT ON COLUMN public.legal_risk_alerts.alert_type IS 'Type: ppe_violations, repeated_incidents, unsafe_speed, incomplete_meetings, untrained_employees, missing_signatures, unresolved_hazards';

-- ============================================================================
-- PART 10 — UPDATED_AT TRIGGERS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to tables with updated_at
CREATE TRIGGER trg_osha_incidents_updated_at
  BEFORE UPDATE ON public.osha_incidents
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_safety_meetings_updated_at
  BEFORE UPDATE ON public.safety_meetings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_hazard_reports_updated_at
  BEFORE UPDATE ON public.hazard_reports
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_training_records_updated_at
  BEFORE UPDATE ON public.training_records
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_subcontractor_compliance_updated_at
  BEFORE UPDATE ON public.subcontractor_compliance
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_daily_safety_logs_updated_at
  BEFORE UPDATE ON public.daily_safety_logs
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- PART 11 — ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.osha_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.osha_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.safety_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ppe_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hazard_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subcontractor_compliance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_safety_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.legal_risk_alerts ENABLE ROW LEVEL SECURITY;

-- Helper function to check company access
CREATE OR REPLACE FUNCTION public.user_has_company_access(_company_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.roofing_companies rc
    WHERE rc.id = _company_id
      AND (
        rc.owner_id = auth.uid()
        OR EXISTS (
          SELECT 1
          FROM public.workspace_members wm
          JOIN public.roofing_companies rc2 ON rc2.workspace_id = wm.workspace_id
          WHERE wm.user_id = auth.uid()
            AND rc2.id = _company_id
        )
      )
  );
$$;

-- RLS Policies: SELECT (read access)
CREATE POLICY "osha_incidents_select"
  ON public.osha_incidents FOR SELECT
  USING (public.user_has_company_access(company_id));

CREATE POLICY "osha_logs_select"
  ON public.osha_logs FOR SELECT
  USING (public.user_has_company_access(company_id));

CREATE POLICY "safety_meetings_select"
  ON public.safety_meetings FOR SELECT
  USING (public.user_has_company_access(company_id));

CREATE POLICY "ppe_checks_select"
  ON public.ppe_checks FOR SELECT
  USING (public.user_has_company_access(company_id));

CREATE POLICY "hazard_reports_select"
  ON public.hazard_reports FOR SELECT
  USING (public.user_has_company_access(company_id));

CREATE POLICY "training_records_select"
  ON public.training_records FOR SELECT
  USING (public.user_has_company_access(company_id));

CREATE POLICY "subcontractor_compliance_select"
  ON public.subcontractor_compliance FOR SELECT
  USING (public.user_has_company_access(company_id));

CREATE POLICY "daily_safety_logs_select"
  ON public.daily_safety_logs FOR SELECT
  USING (public.user_has_company_access(company_id));

CREATE POLICY "legal_risk_alerts_select"
  ON public.legal_risk_alerts FOR SELECT
  USING (public.user_has_company_access(company_id));

-- RLS Policies: INSERT (create access)
CREATE POLICY "osha_incidents_insert"
  ON public.osha_incidents FOR INSERT
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "osha_logs_insert"
  ON public.osha_logs FOR INSERT
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "safety_meetings_insert"
  ON public.safety_meetings FOR INSERT
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "ppe_checks_insert"
  ON public.ppe_checks FOR INSERT
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "hazard_reports_insert"
  ON public.hazard_reports FOR INSERT
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "training_records_insert"
  ON public.training_records FOR INSERT
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "subcontractor_compliance_insert"
  ON public.subcontractor_compliance FOR INSERT
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "daily_safety_logs_insert"
  ON public.daily_safety_logs FOR INSERT
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "legal_risk_alerts_insert"
  ON public.legal_risk_alerts FOR INSERT
  WITH CHECK (public.user_has_company_access(company_id));

-- RLS Policies: UPDATE (modify access)
CREATE POLICY "osha_incidents_update"
  ON public.osha_incidents FOR UPDATE
  USING (public.user_has_company_access(company_id))
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "osha_logs_update"
  ON public.osha_logs FOR UPDATE
  USING (public.user_has_company_access(company_id))
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "safety_meetings_update"
  ON public.safety_meetings FOR UPDATE
  USING (public.user_has_company_access(company_id))
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "ppe_checks_update"
  ON public.ppe_checks FOR UPDATE
  USING (public.user_has_company_access(company_id))
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "hazard_reports_update"
  ON public.hazard_reports FOR UPDATE
  USING (public.user_has_company_access(company_id))
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "training_records_update"
  ON public.training_records FOR UPDATE
  USING (public.user_has_company_access(company_id))
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "subcontractor_compliance_update"
  ON public.subcontractor_compliance FOR UPDATE
  USING (public.user_has_company_access(company_id))
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "daily_safety_logs_update"
  ON public.daily_safety_logs FOR UPDATE
  USING (public.user_has_company_access(company_id))
  WITH CHECK (public.user_has_company_access(company_id));

CREATE POLICY "legal_risk_alerts_update"
  ON public.legal_risk_alerts FOR UPDATE
  USING (public.user_has_company_access(company_id))
  WITH CHECK (public.user_has_company_access(company_id));

-- ============================================================================
-- PART 12 — OSHA COMPLIANCE ENGINE FUNCTIONS
-- ============================================================================

-- Function: Generate OSHA 300 Log (Annual Log of Work-Related Injuries and Illnesses)
CREATE OR REPLACE FUNCTION public.generate_osha_300_log(
  p_company_id uuid,
  p_year int
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_log_id uuid;
  v_incidents jsonb;
BEGIN
  -- Collect all recordable incidents for the year
  SELECT jsonb_agg(
    jsonb_build_object(
      'id', id,
      'date', date,
      'employee_name', (SELECT first_name || ' ' || last_name FROM public.workforce_employees WHERE id = oi.employee_id),
      'job_location', (SELECT notes FROM public.jobs WHERE id = oi.job_id),
      'description', description,
      'injury_type', injury_type,
      'body_part', body_part,
      'severity', severity
    )
    ORDER BY date
  )
  INTO v_incidents
  FROM public.osha_incidents oi
  WHERE oi.company_id = p_company_id
    AND EXTRACT(YEAR FROM oi.date) = p_year
    AND oi.severity IN ('moderate', 'serious', 'fatal'); -- Only recordable incidents

  -- Create OSHA 300 log entry
  INSERT INTO public.osha_logs (
    company_id,
    form_type,
    year,
    data,
    generated_by
  )
  VALUES (
    p_company_id,
    'OSHA_300',
    p_year,
    jsonb_build_object(
      'incidents', COALESCE(v_incidents, '[]'::jsonb),
      'total_recordable_cases', jsonb_array_length(COALESCE(v_incidents, '[]'::jsonb)),
      'generated_at', now()
    ),
    auth.uid()
  )
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$;

-- Function: Generate OSHA 301 Form (Individual Incident Report)
CREATE OR REPLACE FUNCTION public.generate_osha_301_form(
  p_incident_id uuid
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_log_id uuid;
  v_incident RECORD;
  v_employee_name text;
  v_job_location text;
BEGIN
  -- Get incident details
  SELECT * INTO v_incident
  FROM public.osha_incidents
  WHERE id = p_incident_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Incident not found: %', p_incident_id;
  END IF;

  -- Get employee name
  SELECT first_name || ' ' || last_name INTO v_employee_name
  FROM public.workforce_employees
  WHERE id = v_incident.employee_id;

  -- Get job location
  SELECT notes INTO v_job_location
  FROM public.jobs
  WHERE id = v_incident.job_id;

  -- Create OSHA 301 form
  INSERT INTO public.osha_logs (
    company_id,
    form_type,
    year,
    data,
    generated_by
  )
  VALUES (
    v_incident.company_id,
    'OSHA_301',
    EXTRACT(YEAR FROM v_incident.date),
    jsonb_build_object(
      'incident_id', v_incident.id,
      'date_of_injury', v_incident.date,
      'employee_name', COALESCE(v_employee_name, 'Unknown'),
      'job_location', COALESCE(v_job_location, 'Unknown'),
      'description', v_incident.description,
      'injury_type', v_incident.injury_type,
      'body_part', v_incident.body_part,
      'severity', v_incident.severity,
      'osha_classification', v_incident.osha_classification,
      'root_cause', v_incident.root_cause_summary,
      'corrective_action', v_incident.corrective_action_plan,
      'photos', v_incident.photos,
      'generated_at', now()
    ),
    auth.uid()
  )
  RETURNING id INTO v_log_id;

  -- Mark incident as having 301 form completed
  UPDATE public.osha_incidents
  SET osha_301_completed = true
  WHERE id = p_incident_id;

  RETURN v_log_id;
END;
$$;

-- Function: Generate OSHA 300A Summary (Annual Summary)
CREATE OR REPLACE FUNCTION public.generate_osha_300a_summary(
  p_company_id uuid,
  p_year int
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_log_id uuid;
  v_stats jsonb;
BEGIN
  -- Calculate statistics
  SELECT jsonb_build_object(
    'total_recordable_cases', COUNT(*) FILTER (WHERE severity IN ('moderate', 'serious', 'fatal')),
    'fatalities', COUNT(*) FILTER (WHERE severity = 'fatal'),
    'cases_with_days_away_from_work', COUNT(*) FILTER (WHERE severity IN ('serious', 'fatal')),
    'cases_with_job_transfer_or_restriction', COUNT(*) FILTER (WHERE severity = 'moderate'),
    'other_recordable_cases', COUNT(*) FILTER (WHERE severity = 'moderate'),
    'total_employees', (
      SELECT COUNT(DISTINCT employee_id)
      FROM public.osha_incidents
      WHERE company_id = p_company_id
        AND EXTRACT(YEAR FROM date) = p_year
    )
  )
  INTO v_stats
  FROM public.osha_incidents
  WHERE company_id = p_company_id
    AND EXTRACT(YEAR FROM date) = p_year;

  -- Create OSHA 300A summary
  INSERT INTO public.osha_logs (
    company_id,
    form_type,
    year,
    data,
    generated_by
  )
  VALUES (
    p_company_id,
    'OSHA_300A',
    p_year,
    jsonb_build_object(
      'statistics', v_stats,
      'company_name', (SELECT name FROM public.roofing_companies WHERE id = p_company_id),
      'year', p_year,
      'generated_at', now()
    ),
    auth.uid()
  )
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$;

-- ============================================================================
-- PART 13 — AI INCIDENT DOCUMENTATION FUNCTION
-- ============================================================================

-- Function: AI-Enhanced Incident Documentation
-- This function would typically call an AI service to generate compliance fields
-- For now, it provides a structure that can be enhanced with actual AI integration

CREATE OR REPLACE FUNCTION public.ai_enhance_incident_documentation(
  p_incident_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_incident RECORD;
  v_classification text;
  v_root_cause text;
  v_corrective_action text;
BEGIN
  -- Get incident details
  SELECT * INTO v_incident
  FROM public.osha_incidents
  WHERE id = p_incident_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Incident not found: %', p_incident_id;
  END IF;

  -- AI would analyze the description and generate:
  -- 1. OSHA classification
  -- 2. Root cause summary
  -- 3. Corrective action plan
  
  -- For now, we'll create a basic structure
  -- In production, this would call an AI service (OpenAI, Anthropic, etc.)
  
  v_classification := CASE
    WHEN v_incident.severity = 'fatal' THEN 'Fatality'
    WHEN v_incident.severity = 'serious' THEN 'Serious Injury - Days Away from Work'
    WHEN v_incident.severity = 'moderate' THEN 'Recordable Case'
    ELSE 'First Aid Only'
  END;

  v_root_cause := 'Root cause analysis pending AI review. Description: ' || v_incident.description;
  v_corrective_action := 'Corrective action plan to be developed based on root cause analysis.';

  -- Update incident with AI-generated fields
  UPDATE public.osha_incidents
  SET
    osha_classification = v_classification,
    root_cause_summary = v_root_cause,
    corrective_action_plan = v_corrective_action,
    updated_at = now()
  WHERE id = p_incident_id;
END;
$$;

-- ============================================================================
-- PART 14 — LEGAL RISK ALERT FUNCTIONS
-- ============================================================================

-- Function: Check for PPE Violations and Create Alerts
CREATE OR REPLACE FUNCTION public.check_ppe_violations(
  p_company_id uuid,
  p_days_back int DEFAULT 30
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_violation_count int;
  v_employee_id uuid;
  v_employee_name text;
BEGIN
  -- Find employees with multiple PPE violations in the time period
  FOR v_employee_id, v_violation_count IN
    SELECT employee_id, COUNT(*)
    FROM public.ppe_checks
    WHERE company_id = p_company_id
      AND compliant = false
      AND check_date >= CURRENT_DATE - (p_days_back || ' days')::interval
      AND employee_id IS NOT NULL
    GROUP BY employee_id
    HAVING COUNT(*) >= 3
  LOOP
    -- Get employee name
    SELECT first_name || ' ' || last_name INTO v_employee_name
    FROM public.workforce_employees
    WHERE id = v_employee_id;

    -- Create alert if it doesn't already exist
    INSERT INTO public.legal_risk_alerts (
      company_id,
      alert_type,
      severity,
      title,
      message,
      related_employee_id,
      metadata
    )
    VALUES (
      p_company_id,
      'ppe_violations',
      CASE
        WHEN v_violation_count >= 5 THEN 'critical'
        WHEN v_violation_count >= 3 THEN 'high'
        ELSE 'medium'
      END,
      'Repeated PPE Violations Detected',
      COALESCE(v_employee_name, 'Employee') || ' has ' || v_violation_count || ' PPE violations in the last ' || p_days_back || ' days. Recommend retraining and documentation.',
      v_employee_id,
      jsonb_build_object('violation_count', v_violation_count, 'days_back', p_days_back)
    )
    ON CONFLICT DO NOTHING;
  END LOOP;
END;
$$;

-- Function: Check for Unresolved Hazards
CREATE OR REPLACE FUNCTION public.check_unresolved_hazards(
  p_company_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_critical_count int;
  v_high_count int;
BEGIN
  -- Count unresolved critical hazards
  SELECT COUNT(*) INTO v_critical_count
  FROM public.hazard_reports
  WHERE company_id = p_company_id
    AND resolved = false
    AND severity = 'critical';

  -- Count unresolved high-severity hazards
  SELECT COUNT(*) INTO v_high_count
  FROM public.hazard_reports
  WHERE company_id = p_company_id
    AND resolved = false
    AND severity = 'high';

  -- Create alerts if needed
  IF v_critical_count > 0 THEN
    INSERT INTO public.legal_risk_alerts (
      company_id,
      alert_type,
      severity,
      title,
      message,
      metadata
    )
    VALUES (
      p_company_id,
      'unresolved_hazards',
      'critical',
      'Critical Hazards Unresolved',
      'There are ' || v_critical_count || ' unresolved critical hazards. Immediate action required.',
      jsonb_build_object('critical_count', v_critical_count, 'high_count', v_high_count)
    )
    ON CONFLICT DO NOTHING;
  ELSIF v_high_count >= 3 THEN
    INSERT INTO public.legal_risk_alerts (
      company_id,
      alert_type,
      severity,
      title,
      message,
      metadata
    )
    VALUES (
      p_company_id,
      'unresolved_hazards',
      'high',
      'Multiple High-Severity Hazards Unresolved',
      'There are ' || v_high_count || ' unresolved high-severity hazards. Review and resolve promptly.',
      jsonb_build_object('high_count', v_high_count)
    )
    ON CONFLICT DO NOTHING;
  END IF;
END;
$$;

-- Function: Check for Incomplete Safety Meetings
CREATE OR REPLACE FUNCTION public.check_incomplete_safety_meetings(
  p_company_id uuid,
  p_days_back int DEFAULT 7
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_incomplete_count int;
BEGIN
  -- Count unsigned safety meetings in the time period
  SELECT COUNT(*) INTO v_incomplete_count
  FROM public.safety_meetings
  WHERE company_id = p_company_id
    AND signed = false
    AND date >= CURRENT_DATE - (p_days_back || ' days')::interval;

  IF v_incomplete_count > 0 THEN
    INSERT INTO public.legal_risk_alerts (
      company_id,
      alert_type,
      severity,
      title,
      message,
      metadata
    )
    VALUES (
      p_company_id,
      'missing_signatures',
      'medium',
      'Incomplete Safety Meetings',
      'There are ' || v_incomplete_count || ' safety meetings from the last ' || p_days_back || ' days that have not been signed. Complete documentation required for compliance.',
      jsonb_build_object('incomplete_count', v_incomplete_count, 'days_back', p_days_back)
    )
    ON CONFLICT DO NOTHING;
  END IF;
END;
$$;

-- Function: Check for Expired Training
CREATE OR REPLACE FUNCTION public.check_expired_training(
  p_company_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_expired_count int;
  v_required_expired_count int;
BEGIN
  -- Count all expired training records
  SELECT COUNT(*) INTO v_expired_count
  FROM public.training_records
  WHERE company_id = p_company_id
    AND is_expired = true;

  -- Count expired required training
  SELECT COUNT(*) INTO v_required_expired_count
  FROM public.training_records
  WHERE company_id = p_company_id
    AND is_expired = true
    AND is_required = true;

  IF v_required_expired_count > 0 THEN
    INSERT INTO public.legal_risk_alerts (
      company_id,
      alert_type,
      severity,
      title,
      message,
      metadata
    )
    VALUES (
      p_company_id,
      'untrained_employees',
      'high',
      'Required Training Expired',
      'There are ' || v_required_expired_count || ' expired required training records. Employees must renew training before working on jobs.',
      jsonb_build_object('expired_count', v_expired_count, 'required_expired_count', v_required_expired_count)
    )
    ON CONFLICT DO NOTHING;
  ELSIF v_expired_count > 0 THEN
    INSERT INTO public.legal_risk_alerts (
      company_id,
      alert_type,
      severity,
      title,
      message,
      metadata
    )
    VALUES (
      p_company_id,
      'untrained_employees',
      'medium',
      'Training Records Expired',
      'There are ' || v_expired_count || ' expired training records. Review and renew as needed.',
      jsonb_build_object('expired_count', v_expired_count)
    )
    ON CONFLICT DO NOTHING;
  END IF;
END;
$$;

-- Function: Check for Non-Compliant Subcontractors
CREATE OR REPLACE FUNCTION public.check_subcontractor_compliance(
  p_company_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_non_compliant_count int;
  v_sub_name text;
BEGIN
  -- Find non-compliant subcontractors
  FOR v_sub_name IN
    SELECT subcontractor_name
    FROM public.subcontractor_compliance
    WHERE company_id = p_company_id
      AND is_compliant = false
  LOOP
    INSERT INTO public.legal_risk_alerts (
      company_id,
      alert_type,
      severity,
      title,
      message,
      metadata
    )
    VALUES (
      p_company_id,
      'subcontractor_compliance',
      'high',
      'Non-Compliant Subcontractor',
      v_sub_name || ' is not compliant. Cannot be assigned new jobs until compliance documents are updated.',
      jsonb_build_object('subcontractor_name', v_sub_name)
    )
    ON CONFLICT DO NOTHING;
  END LOOP;
END;
$$;

-- ============================================================================
-- PART 15 — COMPLIANCE AUDIT DASHBOARD FUNCTION
-- ============================================================================

-- Function: Get Compliance Dashboard Data
CREATE OR REPLACE FUNCTION public.get_compliance_dashboard(
  p_company_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
AS $$
DECLARE
  v_result jsonb;
  v_safety_score numeric;
  v_incidents_this_year int;
  v_training_compliant_pct numeric;
  v_sub_compliance_pct numeric;
  v_hazards_unresolved int;
  v_osha_ready boolean;
BEGIN
  -- Calculate Safety Score (0-100)
  -- Based on: incidents, training compliance, PPE compliance, hazard resolution
  SELECT
    GREATEST(0, 100 - (
      (COUNT(*) FILTER (WHERE severity IN ('serious', 'fatal'))) * 10 +
      (COUNT(*) FILTER (WHERE severity = 'moderate')) * 5
    ))
  INTO v_safety_score
  FROM public.osha_incidents
  WHERE company_id = p_company_id
    AND EXTRACT(YEAR FROM date) = EXTRACT(YEAR FROM CURRENT_DATE);

  -- Count incidents this year
  SELECT COUNT(*) INTO v_incidents_this_year
  FROM public.osha_incidents
  WHERE company_id = p_company_id
    AND EXTRACT(YEAR FROM date) = EXTRACT(YEAR FROM CURRENT_DATE);

  -- Calculate training compliance percentage
  SELECT
    CASE
      WHEN COUNT(*) = 0 THEN 100
      ELSE ROUND((COUNT(*) FILTER (WHERE is_expired = false AND is_required = true)::numeric / 
                  NULLIF(COUNT(*) FILTER (WHERE is_required = true), 0)) * 100, 1)
    END
  INTO v_training_compliant_pct
  FROM public.training_records
  WHERE company_id = p_company_id;

  -- Calculate subcontractor compliance percentage
  SELECT
    CASE
      WHEN COUNT(*) = 0 THEN 100
      ELSE ROUND((COUNT(*) FILTER (WHERE is_compliant = true)::numeric / 
                  NULLIF(COUNT(*), 0)) * 100, 1)
    END
  INTO v_sub_compliance_pct
  FROM public.subcontractor_compliance
  WHERE company_id = p_company_id;

  -- Count unresolved hazards
  SELECT COUNT(*) INTO v_hazards_unresolved
  FROM public.hazard_reports
  WHERE company_id = p_company_id
    AND resolved = false;

  -- Check OSHA readiness (has logs for current year)
  SELECT EXISTS (
    SELECT 1
    FROM public.osha_logs
    WHERE company_id = p_company_id
      AND form_type = 'OSHA_300A'
      AND year = EXTRACT(YEAR FROM CURRENT_DATE)
  ) INTO v_osha_ready;

  -- Build result
  v_result := jsonb_build_object(
    'safety_score', COALESCE(v_safety_score, 100),
    'incidents_this_year', v_incidents_this_year,
    'training_compliant_pct', COALESCE(v_training_compliant_pct, 100),
    'sub_compliance_pct', COALESCE(v_sub_compliance_pct, 100),
    'hazards_unresolved', v_hazards_unresolved,
    'osha_requirements_ready', v_osha_ready,
    'generated_at', now()
  );

  RETURN v_result;
END;
$$;

-- ============================================================================
-- PART 16 — DAILY SAFETY LOG AUTOMATION FUNCTION
-- ============================================================================

-- Function: Create Daily Safety Log for Job
CREATE OR REPLACE FUNCTION public.create_daily_safety_log(
  p_company_id uuid,
  p_job_id uuid,
  p_log_date date DEFAULT CURRENT_DATE
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_log_id uuid;
BEGIN
  -- Create daily safety log
  INSERT INTO public.daily_safety_logs (
    company_id,
    job_id,
    log_date
  )
  VALUES (
    p_company_id,
    p_job_id,
    p_log_date
  )
  ON CONFLICT (job_id, log_date) DO UPDATE SET
    updated_at = now()
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$;

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON FUNCTION public.generate_osha_300_log IS 'Generates OSHA 300 log for a given company and year (Block 254600)';
COMMENT ON FUNCTION public.generate_osha_301_form IS 'Generates OSHA 301 form for a specific incident (Block 254600)';
COMMENT ON FUNCTION public.generate_osha_300a_summary IS 'Generates OSHA 300A annual summary (Block 254600)';
COMMENT ON FUNCTION public.ai_enhance_incident_documentation IS 'AI-enhanced incident documentation (Block 254600)';
COMMENT ON FUNCTION public.check_ppe_violations IS 'Checks for PPE violations and creates alerts (Block 254600)';
COMMENT ON FUNCTION public.check_unresolved_hazards IS 'Checks for unresolved hazards and creates alerts (Block 254600)';
COMMENT ON FUNCTION public.check_incomplete_safety_meetings IS 'Checks for incomplete safety meetings (Block 254600)';
COMMENT ON FUNCTION public.check_expired_training IS 'Checks for expired training records (Block 254600)';
COMMENT ON FUNCTION public.check_subcontractor_compliance IS 'Checks subcontractor compliance status (Block 254600)';
COMMENT ON FUNCTION public.get_compliance_dashboard IS 'Returns compliance dashboard data (Block 254600)';
COMMENT ON FUNCTION public.create_daily_safety_log IS 'Creates daily safety log for a job (Block 254600)';

-- ============================================================================
-- PART 17 — AI PPE VERIFICATION FUNCTION
-- ============================================================================

-- Function: AI PPE Verification from Photo
-- This function would typically call an AI service to analyze a photo
-- For now, it provides a structure that can be enhanced with actual AI integration

CREATE OR REPLACE FUNCTION public.ai_verify_ppe_from_photo(
  p_ppe_check_id uuid,
  p_photo_url text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_ppe_check RECORD;
  v_hard_hat boolean := false;
  v_harness boolean := false;
  v_boots boolean := false;
  v_eye_protection boolean := false;
  v_vest boolean := false;
  v_gloves boolean := false;
  v_confidence numeric := 0;
  v_notes text := '';
BEGIN
  -- Get PPE check record
  SELECT * INTO v_ppe_check
  FROM public.ppe_checks
  WHERE id = p_ppe_check_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'PPE check not found: %', p_ppe_check_id;
  END IF;

  -- AI would analyze the photo and detect:
  -- - Hard hat presence
  -- - Safety vest presence
  -- - Boots presence
  -- - Eye protection presence
  -- - Harness presence (if on roof)
  -- - Gloves presence
  
  -- For now, we'll create a placeholder structure
  -- In production, this would call an AI service (OpenAI Vision, Google Vision, etc.)
  -- Example: Call AI service with photo_url and get structured response
  
  -- Placeholder logic (replace with actual AI call):
  -- v_hard_hat := ai_service.detect_object(p_photo_url, 'hard_hat');
  -- v_vest := ai_service.detect_object(p_photo_url, 'safety_vest');
  -- etc.
  
  -- For now, we'll set a default that requires manual verification
  v_notes := 'AI verification pending. Please verify manually or integrate AI service.';
  v_confidence := 0;

  -- Update PPE check with AI results
  UPDATE public.ppe_checks
  SET
    photo_url = p_photo_url,
    hard_hat = v_hard_hat,
    harness = v_harness,
    boots = v_boots,
    eye_protection = v_eye_protection,
    vest = v_vest,
    gloves = v_gloves,
    ai_verified = true,
    ai_confidence = v_confidence,
    ai_notes = v_notes,
    compliant = (v_hard_hat AND v_vest AND v_boots AND v_eye_protection),
    updated_at = now()
  WHERE id = p_ppe_check_id;

  -- If not compliant, create a violation alert
  IF NOT (v_hard_hat AND v_vest AND v_boots AND v_eye_protection) THEN
    INSERT INTO public.legal_risk_alerts (
      company_id,
      alert_type,
      severity,
      title,
      message,
      related_employee_id,
      related_job_id,
      metadata
    )
    VALUES (
      v_ppe_check.company_id,
      'ppe_violations',
      'medium',
      'PPE Violation Detected',
      'AI detected missing PPE items. Review required.',
      v_ppe_check.employee_id,
      v_ppe_check.job_id,
      jsonb_build_object(
        'ppe_check_id', p_ppe_check_id,
        'hard_hat', v_hard_hat,
        'vest', v_vest,
        'boots', v_boots,
        'eye_protection', v_eye_protection
      )
    )
    ON CONFLICT DO NOTHING;
  END IF;
END;
$$;

-- ============================================================================
-- PART 18 — COMPREHENSIVE RISK CHECK FUNCTION
-- ============================================================================

-- Function: Run All Legal Risk Checks
-- This function runs all risk check functions and can be scheduled via cron

CREATE OR REPLACE FUNCTION public.run_all_legal_risk_checks(
  p_company_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Run all risk check functions
  PERFORM public.check_ppe_violations(p_company_id, 30);
  PERFORM public.check_unresolved_hazards(p_company_id);
  PERFORM public.check_incomplete_safety_meetings(p_company_id, 7);
  PERFORM public.check_expired_training(p_company_id);
  PERFORM public.check_subcontractor_compliance(p_company_id);
END;
$$;

-- ============================================================================
-- PART 19 — AUTOMATED DAILY SAFETY LOG REMINDER FUNCTION
-- ============================================================================

-- Function: Get Jobs Missing Daily Safety Logs
-- Returns jobs that need daily safety logs for today

CREATE OR REPLACE FUNCTION public.get_jobs_missing_safety_logs(
  p_company_id uuid,
  p_log_date date DEFAULT CURRENT_DATE
)
RETURNS TABLE (
  job_id uuid,
  job_notes text,
  crew_foreman_id uuid,
  foreman_name text
)
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
AS $$
BEGIN
  RETURN QUERY
  SELECT DISTINCT
    j.id AS job_id,
    j.notes AS job_notes,
    we.id AS crew_foreman_id,
    (we.first_name || ' ' || we.last_name) AS foreman_name
  FROM public.jobs j
  LEFT JOIN public.daily_safety_logs dsl ON dsl.job_id = j.id AND dsl.log_date = p_log_date
  LEFT JOIN public.crew_assignments ca ON ca.job_id = j.id
  LEFT JOIN public.workforce_employees we ON we.id = ca.employee_id AND we.role = 'foreman'
  WHERE dsl.id IS NULL -- No safety log for this date
    AND j.stage IN ('scheduled', 'in_progress') -- Only active jobs
    AND EXISTS (
      -- Verify company access through crew assignments
      SELECT 1
      FROM public.crew_assignments ca2
      JOIN public.workforce_employees we2 ON we2.id = ca2.employee_id
      WHERE ca2.job_id = j.id
        AND we2.company_id = p_company_id
    )
  ORDER BY j.id;
END;
$$;

COMMENT ON FUNCTION public.ai_verify_ppe_from_photo IS 'AI-powered PPE verification from photo (Block 254600)';
COMMENT ON FUNCTION public.run_all_legal_risk_checks IS 'Runs all legal risk check functions for a company (Block 254600)';
COMMENT ON FUNCTION public.get_jobs_missing_safety_logs IS 'Returns jobs missing daily safety logs for a given date (Block 254600)';






















