-- A/B Testing: Templates and Variants
-- Base template per campaign
create table if not exists campaign_templates (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references campaigns(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Default',
  subject text not null,
  body_html text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_campaign_templates_campaign_user on campaign_templates(campaign_id, user_id);
create index if not exists idx_campaign_templates_active on campaign_templates(is_active) where is_active = true;

-- Variants generated by AI
create table if not exists template_variants (
  id uuid primary key default gen_random_uuid(),
  campaign_template_id uuid not null references campaign_templates(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null,                   -- e.g. "V1: Curious hook"
  subject text not null,
  body_html text not null,
  weight int not null default 50,        -- % for splitting (sum normalized per campaign)
  created_at timestamptz not null default now()
);

create index if not exists idx_template_variants_template on template_variants(campaign_template_id);
create index if not exists idx_template_variants_user on template_variants(user_id);

-- Link sends to variant for analytics
alter table email_logs
  add column if not exists template_variant_id uuid references template_variants(id);

create index if not exists idx_email_logs_variant on email_logs(template_variant_id);

-- Variant roll-up metrics view
create or replace view variant_metrics as
select
  tv.id as variant_id,
  tv.label,
  tv.weight,
  ct.campaign_id,
  count(el.id)::int as sent,
  sum((el.opened = true)::int)::int as opens,
  sum((el.clicked = true)::int)::int as clicks,
  sum((el.replied = true)::int)::int as replies,
  round(100.0 * sum((el.opened = true)::int) / nullif(count(el.id),0), 2) as open_rate,
  round(100.0 * sum((el.clicked = true)::int) / nullif(count(el.id),0), 2) as click_rate,
  round(100.0 * sum((el.replied = true)::int) / nullif(count(el.id),0), 2) as reply_rate
from template_variants tv
join campaign_templates ct on ct.id = tv.campaign_template_id
left join email_logs el on el.template_variant_id = tv.id
group by tv.id, tv.label, tv.weight, ct.campaign_id;

-- RLS policies for campaign_templates
alter table campaign_templates enable row level security;

drop policy if exists "campaign_templates_select_own" on campaign_templates;
create policy "campaign_templates_select_own"
on campaign_templates for select
using (auth.uid() = user_id);

drop policy if exists "campaign_templates_insert_own" on campaign_templates;
create policy "campaign_templates_insert_own"
on campaign_templates for insert
with check (auth.uid() = user_id);

drop policy if exists "campaign_templates_update_own" on campaign_templates;
create policy "campaign_templates_update_own"
on campaign_templates for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- RLS policies for template_variants
alter table template_variants enable row level security;

drop policy if exists "template_variants_select_own" on template_variants;
create policy "template_variants_select_own"
on template_variants for select
using (auth.uid() = user_id);

drop policy if exists "template_variants_insert_own" on template_variants;
create policy "template_variants_insert_own"
on template_variants for insert
with check (auth.uid() = user_id);

drop policy if exists "template_variants_update_own" on template_variants;
create policy "template_variants_update_own"
on template_variants for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Helper view to pick winners per campaign (optional)
create or replace view variant_winners as
select campaign_id, variant_id
from (
  select vm.*, row_number() over (partition by campaign_id order by reply_rate desc nulls last, sent desc) as rk
  from variant_metrics vm
) x
where rk = 1 and sent >= 50; -- only if enough volume