/**
 * Minimal ICS generator (no deps).
 * Creates a single VEVENT with basic fields and returns a text/calendar string.
 */
export type ICSOptions = {
  uid?: string;               // if omitted, autogenerated
  title: string;              // SUMMARY
  description?: string;       // DESCRIPTION
  location?: string;          // LOCATION
  organizer?: { name?: string; email: string };
  attendee?: { name?: string; email: string } | { name?: string; email: string }[];
  start: Date;                // UTC or local; will be converted to UTC (Z)
  end: Date;                  // same as start
  url?: string;               // optional booking url
};

function dtstamp(date: Date) {
  const d = new Date(date);
  const yyyy = d.getUTCFullYear().toString().padStart(4, "0");
  const mm = (d.getUTCMonth() + 1).toString().padStart(2, "0");
  const dd = d.getUTCDate().toString().padStart(2, "0");
  const hh = d.getUTCHours().toString().padStart(2, "0");
  const min = d.getUTCMinutes().toString().padStart(2, "0");
  const ss = d.getUTCSeconds().toString().padStart(2, "0");
  return `${yyyy}${mm}${dd}T${hh}${min}${ss}Z`;
}

function escapeText(s: string) {
  return s.replace(/\\/g, "\\\\").replace(/;/g, "\\;").replace(/,/g, "\\,").replace(/\n/g, "\\n");
}

export function buildICS(opts: ICSOptions): string {
  const uid = opts.uid || `${Date.now()}-${Math.random().toString(36).slice(2)}@smartsend.ai`;
  const lines: string[] = [];
  lines.push("BEGIN:VCALENDAR");
  lines.push("VERSION:2.0");
  lines.push("PRODID:-//SmartSendAI//EN");
  lines.push("CALSCALE:GREGORIAN");
  lines.push("METHOD:REQUEST");

  lines.push("BEGIN:VEVENT");
  lines.push(`UID:${uid}`);
  lines.push(`DTSTAMP:${dtstamp(new Date())}`);
  lines.push(`DTSTART:${dtstamp(opts.start)}`);
  lines.push(`DTEND:${dtstamp(opts.end)}`);
  lines.push(`SUMMARY:${escapeText(opts.title)}`);

  if (opts.description) lines.push(`DESCRIPTION:${escapeText(opts.description)}`);
  if (opts.location) lines.push(`LOCATION:${escapeText(opts.location)}`);
  if (opts.url) lines.push(`URL:${escapeText(opts.url)}`);

  if (opts.organizer) {
    const cn = opts.organizer.name ? `CN=${escapeText(opts.organizer.name)}:` : "";
    lines.push(`ORGANIZER;${cn}mailto:${opts.organizer.email}`);
  }
  const attendees = Array.isArray(opts.attendee) ? opts.attendee : opts.attendee ? [opts.attendee] : [];
  for (const a of attendees) {
    const cn = a.name ? `CN=${escapeText(a.name)};` : "";
    lines.push(`ATTENDEE;${cn}ROLE=REQ-PARTICIPANT:mailto:${a.email}`);
  }

  lines.push("END:VEVENT");
  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}